"""Tests for VirSci idea integration across the BFTS pipeline.

Verifies that ideas generated by generate_ideas() flow correctly through:
1. loop.py: idea injection into LLM conversation
2. bfts.py: idea context in expand() prompt
3. pipeline.py: idea.json loaded into paper context + template vars
4. pipeline.py: evaluation_criteria fallback to idea.json
5. loop.py: memory.add() (not memory.write()) for evaluation criteria
"""

import json
from pathlib import Path
from unittest import mock
from unittest.mock import MagicMock

import pytest

from ari.orchestrator.node import Node, NodeStatus


# ══════════════════════════════════════════════
# Fixtures
# ══════════════════════════════════════════════

SAMPLE_IDEA_DATA = {
    "gap_analysis": "Most CPU CSR SpMM work optimizes for narrow RHS widths",
    "ideas": [
        {
            "title": "RHC: Isolated RHS Hotset Cache",
            "description": "Combines selective hotset materialization with contention isolation",
            "experiment_plan": "Implement hotset cache, sweep K=1..256, measure GFLOP/s",
            "novelty": "Novelty score: 8",
            "feasibility": "Feasibility score: 7",
            "novelty_score": 0.8,
            "feasibility_score": 0.7,
            "overall_score": 0.77,
        },
        {
            "title": "PAL-CLCS: Pressure-Augmented Loopline",
            "description": "Closed-loop concurrency shaping for K-robust CSR SpMM",
            "experiment_plan": "Implement feedback controller with PMU signals",
            "novelty_score": 0.8,
            "feasibility_score": 0.7,
            "overall_score": 0.77,
        },
    ],
    "primary_metric": "GFlops_per_s",
    "higher_is_better": True,
    "metric_rationale": "Throughput is the primary performance indicator",
}


@pytest.fixture
def fake_nodes():
    n = Node(id="node_root", parent_id=None, depth=0)
    n.status = NodeStatus.SUCCESS
    n.has_real_data = True
    n.metrics = {"GFlops_per_s": 21.26, "_scientific_score": 0.6}
    n.eval_summary = "CSR SpMM baseline with roofline model"
    return [n]


@pytest.fixture
def checkpoint_with_idea(tmp_path):
    """Create checkpoint dir with idea.json."""
    ckpt = tmp_path / "ckpt"
    ckpt.mkdir()
    (ckpt / "idea.json").write_text(json.dumps(SAMPLE_IDEA_DATA, ensure_ascii=False))
    return ckpt


@pytest.fixture
def checkpoint_without_idea(tmp_path):
    ckpt = tmp_path / "ckpt"
    ckpt.mkdir()
    return ckpt


# ══════════════════════════════════════════════
# 1. BFTS expand: idea_context reaches prompt
# ══════════════════════════════════════════════

class TestBFTSExpandIdeaContext:
    def test_expand_includes_idea_context_in_prompt(self):
        """expand() must include idea_context in the LLM prompt."""
        from ari.config import BFTSConfig
        from ari.llm.client import LLMResponse
        from ari.orchestrator.bfts import BFTS

        mock_llm = MagicMock()
        mock_llm.complete.return_value = LLMResponse(
            content='[{"label": "improve", "direction": "Implement hotset cache"}]'
        )

        bfts = BFTS(BFTSConfig(max_depth=3, max_retries_per_node=2, max_total_nodes=10), mock_llm)
        node = Node(id="n1", parent_id=None, depth=0, has_real_data=True,
                    metrics={"GFlops_per_s": 21.0})

        idea_ctx = "Gap: narrow RHS\nIdea: RHC Hotset Cache\nDescription: selective materialization"
        children = bfts.expand(node, experiment_goal="CSR SpMM benchmark", idea_context=idea_ctx)

        # Verify idea context was included in the LLM prompt
        prompt_sent = mock_llm.complete.call_args[0][0][0].content
        assert "RHC Hotset Cache" in prompt_sent
        assert "selective materialization" in prompt_sent
        assert len(children) == 1

    def test_expand_works_without_idea_context(self):
        """expand() must work with empty idea_context (backward compatible)."""
        from ari.config import BFTSConfig
        from ari.llm.client import LLMResponse
        from ari.orchestrator.bfts import BFTS

        mock_llm = MagicMock()
        mock_llm.complete.return_value = LLMResponse(
            content='[{"label": "improve", "direction": "Tune params"}]'
        )

        bfts = BFTS(BFTSConfig(max_depth=3, max_retries_per_node=2, max_total_nodes=10), mock_llm)
        node = Node(id="n1", parent_id=None, depth=0, has_real_data=True)

        children = bfts.expand(node, experiment_goal="test")  # no idea_context
        assert len(children) == 1

        prompt_sent = mock_llm.complete.call_args[0][0][0].content
        assert "VirSci" not in prompt_sent  # no idea block when empty


# ══════════════════════════════════════════════
# 2. Pipeline: idea.json loaded into paper context
# ══════════════════════════════════════════════

class TestPipelineIdeaLoading:
    def test_idea_json_merged_into_paper_context(
        self, checkpoint_with_idea, fake_nodes
    ):
        """idea.json content must appear in paper_context template var."""
        from ari.pipeline import run_pipeline

        captured_args = {}

        def fake_subprocess(tool, args, config_path, skill_name=""):
            captured_args[tool] = dict(args)
            return {"result": "ok"}

        stages = [{
            "stage": "test_stage", "skill": "test-skill", "tool": "test_tool",
            "depends_on": [], "inputs": {"ctx": "{{paper_context}}"},
            "outputs": {}, "skip_if_exists": "",
        }]

        with mock.patch("ari.pipeline._run_stage_subprocess", side_effect=fake_subprocess):
            run_pipeline(
                stages, fake_nodes,
                {"goal": "CSR SpMM", "topic": "test", "file": ""},
                checkpoint_with_idea, "",
            )

        resolved_ctx = captured_args["test_tool"]["ctx"]
        assert "RHC" in resolved_ctx or "Hotset Cache" in resolved_ctx, \
            f"Idea title must appear in paper_context, got: {resolved_ctx[:200]}"
        assert "narrow RHS" in resolved_ctx.lower() or "gap" in resolved_ctx.lower(), \
            "Gap analysis must appear in paper_context"

    def test_idea_context_template_var_available(
        self, checkpoint_with_idea, fake_nodes
    ):
        """{{idea_context}} template must resolve to idea content."""
        from ari.pipeline import run_pipeline

        captured_args = {}

        def fake_subprocess(tool, args, config_path, skill_name=""):
            captured_args[tool] = dict(args)
            return {"result": "ok"}

        stages = [{
            "stage": "test_stage", "skill": "test-skill", "tool": "test_tool",
            "depends_on": [], "inputs": {"idea": "{{idea_context}}"},
            "outputs": {}, "skip_if_exists": "",
        }]

        with mock.patch("ari.pipeline._run_stage_subprocess", side_effect=fake_subprocess):
            run_pipeline(
                stages, fake_nodes,
                {"goal": "test", "topic": "test", "file": ""},
                checkpoint_with_idea, "",
            )

        idea_val = captured_args["test_tool"]["idea"]
        assert "RHC" in idea_val or "Hotset Cache" in idea_val, \
            f"{{{{idea_context}}}} must resolve to idea content, got: {idea_val[:200]}"

    def test_no_idea_json_graceful_degradation(
        self, checkpoint_without_idea, fake_nodes
    ):
        """Missing idea.json must not crash, paper_context still works."""
        from ari.pipeline import run_pipeline

        captured_args = {}

        def fake_subprocess(tool, args, config_path, skill_name=""):
            captured_args[tool] = dict(args)
            return {"result": "ok"}

        stages = [{
            "stage": "test_stage", "skill": "test-skill", "tool": "test_tool",
            "depends_on": [],
            "inputs": {"ctx": "{{paper_context}}", "idea": "{{idea_context}}"},
            "outputs": {}, "skip_if_exists": "",
        }]

        with mock.patch("ari.pipeline._run_stage_subprocess", side_effect=fake_subprocess):
            run_pipeline(
                stages, fake_nodes,
                {"goal": "test", "topic": "test", "file": ""},
                checkpoint_without_idea, "",
            )

        # paper_context should still work (just without idea content)
        assert "test_tool" in captured_args
        # idea_context should be empty string, not crash
        assert captured_args["test_tool"]["idea"] == ""


# ══════════════════════════════════════════════
# 3. Evaluation criteria fallback to idea.json
# ══════════════════════════════════════════════

class TestEvalCriteriaFallback:
    def test_eval_criteria_from_idea_json(
        self, checkpoint_with_idea, fake_nodes
    ):
        """When memory_snapshot is empty, eval criteria should fall back to idea.json."""
        from ari.pipeline import run_pipeline

        stages = [{
            "stage": "test_stage", "skill": "test-skill", "tool": "test_tool",
            "depends_on": [], "inputs": {}, "outputs": {}, "skip_if_exists": "",
        }]

        with mock.patch("ari.pipeline._run_stage_subprocess", return_value={"result": "ok"}):
            run_pipeline(
                stages, fake_nodes,
                {"goal": "test", "topic": "test", "file": ""},
                checkpoint_with_idea, "",
            )

        ec_path = checkpoint_with_idea / "evaluation_criteria.json"
        assert ec_path.exists(), "evaluation_criteria.json must be created"
        ec = json.loads(ec_path.read_text())
        assert ec["primary_metric"] == "GFlops_per_s", \
            f"primary_metric must come from idea.json, got: {ec['primary_metric']}"
        assert ec["higher_is_better"] is True

    def test_eval_criteria_empty_without_idea(
        self, checkpoint_without_idea, fake_nodes
    ):
        """Without idea.json and memory_snapshot, eval criteria should be empty."""
        from ari.pipeline import run_pipeline

        stages = [{
            "stage": "test_stage", "skill": "test-skill", "tool": "test_tool",
            "depends_on": [], "inputs": {}, "outputs": {}, "skip_if_exists": "",
        }]

        with mock.patch("ari.pipeline._run_stage_subprocess", return_value={"result": "ok"}):
            run_pipeline(
                stages, fake_nodes,
                {"goal": "test", "topic": "test", "file": ""},
                checkpoint_without_idea, "",
            )

        ec_path = checkpoint_without_idea / "evaluation_criteria.json"
        assert ec_path.exists()
        ec = json.loads(ec_path.read_text())
        assert ec["primary_metric"] == ""


# ══════════════════════════════════════════════
# 4. Memory API: memory.add() not memory.write()
# ══════════════════════════════════════════════

class TestMemoryAPICorrectness:
    def test_memory_client_has_add_not_write(self):
        """MemoryClient must expose add(), not write()."""
        from ari.memory.client import MemoryClient
        assert hasattr(MemoryClient, "add"), "MemoryClient must have add()"
        assert not hasattr(MemoryClient, "write"), "MemoryClient must NOT have write()"

    def test_file_memory_client_add_works(self, tmp_path):
        """FileMemoryClient.add() must persist and be searchable."""
        from ari.memory.file_client import FileMemoryClient
        mc = FileMemoryClient(str(tmp_path / "mem.json"))
        mc.add(
            "EVALUATION_CRITERIA: primary_metric=GFlops_per_s higher_is_better=True",
            metadata={"type": "evaluation_criteria"},
        )
        results = mc.search("GFlops")
        assert len(results) >= 1
        assert "GFlops_per_s" in results[0]["content"]

    def test_loop_uses_memory_add_not_write(self):
        """loop.py must use self.memory.add(), not self.memory.write()."""
        src = Path(__file__).parent.parent / "ari" / "agent" / "loop.py"
        content = src.read_text()
        # Find the EVALUATION_CRITERIA block
        idx = content.find("EVALUATION_CRITERIA:")
        assert idx > 0, "EVALUATION_CRITERIA block must exist"
        block = content[max(0, idx - 200):idx + 200]
        assert "self.memory.add(" in block, \
            "Must use self.memory.add(), not self.memory.write()"
        assert "self.memory.write(" not in block, \
            "self.memory.write() is a bug — MemoryClient has no write() method"


# ══════════════════════════════════════════════
# 5. Template resolution: _resolve_templates
# ══════════════════════════════════════════════

class TestTemplateResolution:
    def test_idea_context_resolves(self):
        """{{idea_context}} must resolve in _resolve_templates."""
        from ari.pipeline import _resolve_templates

        tpl_vars = {
            "idea_context": "Research direction: RHC Hotset Cache",
            "paper_context": "Full context including idea",
        }
        result = _resolve_templates("Idea: {{idea_context}}", tpl_vars)
        assert result == "Idea: Research direction: RHC Hotset Cache"

    def test_paper_context_includes_idea(self):
        """{{paper_context}} must include idea content when idea.json exists."""
        from ari.pipeline import _resolve_templates

        tpl_vars = {
            "idea_context": "RHC Hotset Cache idea",
            "paper_context": "Static context\n\nRHC Hotset Cache idea\n\nExperiment results",
        }
        result = _resolve_templates("{{paper_context}}", tpl_vars)
        assert "RHC Hotset Cache" in result

    def test_empty_idea_context_resolves_to_empty(self):
        """{{idea_context}} resolves to empty string when no idea.json."""
        from ari.pipeline import _resolve_templates

        tpl_vars = {"idea_context": "", "paper_context": "just results"}
        result = _resolve_templates("prefix-{{idea_context}}-suffix", tpl_vars)
        assert result == "prefix--suffix"

    def test_dot_notation_still_works(self):
        """Dot-notation resolution must not regress."""
        from ari.pipeline import _resolve_templates

        tpl_vars = {
            "stages": {"write_paper": {"outputs": {"file": "/tmp/paper.tex"}}},
        }
        result = _resolve_templates("{{stages.write_paper.outputs.file}}", tpl_vars)
        assert result == "/tmp/paper.tex"


# ══════════════════════════════════════════════
# 6. CLI _run_loop: idea.json lazy-loaded for expand
# ══════════════════════════════════════════════

class TestCliIdeaLoading:
    def test_run_loop_loads_idea_json_for_expand(self):
        """_run_loop must load idea.json and pass idea_context to bfts.expand()."""
        src = Path(__file__).parent.parent / "ari" / "cli.py"
        content = src.read_text()
        assert "idea.json" in content, "cli.py must reference idea.json"
        assert "idea_context" in content, "cli.py must pass idea_context"
        # Verify expand call includes idea_context parameter
        assert "idea_context=_idea_ctx_for_expand" in content, \
            "bfts.expand() must receive idea_context from cli.py"
