"""Tests for the Experiment Artifact Repository (issue #4).

The layout is *node_report-driven*:

    <checkpoint>/
    ├── EVOLUTION.md         ← ARI audit log (search trajectory)
    ├── _provenance.json     ← ARI audit log (per-file origin)
    └── ear/
        ├── README.md
        ├── reproduce.sh
        ├── environment.json
        ├── code/                ← verbatim from contributing chain nodes
        ├── data/                ← uploads/ mirror (input only; absent if no uploads)
        ├── figures/             ← top-level *.{pdf,png,svg,jpg,jpeg}
        └── LICENSE              ← optional, SPDX template

EVOLUTION.md and _provenance.json are kept alongside the checkpoint, *not*
inside ear/, so they are never bundled into the published artifact.

Other internal ARI metadata (tree.json, science_data.json, raw_metrics.json,
eval_scores.json, commands.md) also stays at checkpoint root. Experiment
outputs (CSV/log/binary) are not bundled — they are regenerated by
reproduce.sh.

Tests T-C1..T-C18 cover the spec; older tests target the API stability of
the GUI surface (`_api_ear`) and the workflow.yaml stage ordering.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import pytest
import yaml

# Make sure ari-skill-transform/src is importable
_TRANSFORM_SRC = (
    Path(__file__).parent.parent.parent / "ari-skill-transform" / "src"
).resolve()
if str(_TRANSFORM_SRC) not in sys.path:
    sys.path.insert(0, str(_TRANSFORM_SRC))


# ── helpers ─────────────────────────────────────────────────────────────


def _get_generate_ear():
    """Import generate_ear from ari-skill-transform/src/server.py."""
    import importlib

    ts = str(_TRANSFORM_SRC)
    if ts in sys.path:
        sys.path.remove(ts)
    sys.path.insert(0, ts)

    if "server" in sys.modules:
        del sys.modules["server"]
    module = importlib.import_module("server")
    fn = module.generate_ear
    if hasattr(fn, "fn"):
        fn = fn.fn
    elif hasattr(fn, "__wrapped__"):
        fn = fn.__wrapped__
    return fn


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _make_chain_checkpoint(tmp_path: Path, *, with_uploads: bool = False,
                           with_figures: bool = False,
                           with_publish_license: str | None = None) -> Path:
    """Build a 3-node draft → improve → validation checkpoint with reports.

    Each node has a real work_dir under experiments/<run_id>/<node_id>/, and a
    node_report.json describing its contribution. The validation node is best
    (highest scientific_score) but contributes no new files — it must still
    appear in the chain via always_include.
    """
    workspace = tmp_path / "ws"
    run_id = "exp_run"
    ckpt = workspace / "checkpoints" / run_id
    ckpt.mkdir(parents=True)
    exp_root = workspace / "experiments" / run_id

    # Set up work_dirs.
    nodes_def = [
        ("node_draft",      None,           0, "draft",
         {"throughput": 100.0, "_scientific_score": 0.45},
         {"main.cpp": "int main(){return 0;}\n",
          "run_job.sh": "#!/bin/bash\ng++ -O2 main.cpp -o main\n./main --out result.csv\n"},
         "Initial naïve baseline.",
         {"added": ["main.cpp", "run_job.sh"], "modified": []}),
        ("node_improve",    "node_draft",   1, "improve",
         {"throughput": 175.5, "_scientific_score": 0.82},
         {"main.cpp": "int main(){/* tiled */ return 0;}\n",  # modified
          "run_job.sh": "#!/bin/bash\ng++ -O3 main.cpp -o main\n./main --out result.csv\n",  # modified
          "tiling.h": "#define TILE 32\n"},  # added
         "Introduced loop tiling (TILE=32).",
         {"added": ["tiling.h"], "modified": ["main.cpp", "run_job.sh"]}),
        ("node_validation", "node_improve", 2, "validation",
         {"throughput": 175.0, "_scientific_score": 0.91},
         {"main.cpp": "int main(){/* tiled */ return 0;}\n",  # inherited
          "run_job.sh": "#!/bin/bash\ng++ -O3 main.cpp -o main\n./main --out result.csv\n",  # inherited
          "tiling.h": "#define TILE 32\n"},  # inherited
         "Re-ran with 5 seeds; variance under 2%.",
         {"added": [], "modified": []}),
    ]

    nodes_dict: list[dict] = []
    for nid, parent, depth, label, metrics, files, delta, fc in nodes_def:
        wd = exp_root / nid
        wd.mkdir(parents=True)
        for fn, body in files.items():
            (wd / fn).write_text(body)
        # Build the node_report.json.
        report = {
            "schema_version": 1,
            "node_id": nid,
            "parent_id": parent,
            "ancestor_ids": [],
            "label": label,
            "raw_label": "",
            "depth": depth,
            "status": "success",
            "started_at": "2026-04-25T00:00:00Z",
            "completed_at": "2026-04-25T00:01:00Z",
            "original_direction": delta,
            "files_changed": {
                "added": [{"path": p, "sha256": _sha256(wd / p)}
                          for p in fc["added"]],
                "modified": [{"path": p,
                              "sha256_before": "0" * 64,
                              "sha256_after": _sha256(wd / p)}
                             for p in fc["modified"]],
                "deleted": [],
                "inherited_unchanged": [],
            },
            "what_was_done": delta,
            "delta_vs_parent": delta,
            "metrics": metrics,
            "self_assessment": {
                "succeeded": True,
                "headline": delta,
                "concerns": ["comparative_rigor: no MKL baseline"]
                            if label == "improve" else [],
            },
            "next_steps_hints": ["Test variance"]
                                if label == "validation" else [],
            "build_command": "g++ -O3 main.cpp -o main"
                             if label == "validation" else "",
            "run_command": "./main --out result.csv"
                           if label == "validation" else "",
            "artifacts": [],
            "evaluator_reason": delta,
            "trace_log_summary": "",
            "migration_source": "fresh",
        }
        (wd / "node_report.json").write_text(json.dumps(report, indent=2))

        nodes_dict.append({
            "id": nid,
            "parent_id": parent,
            "depth": depth,
            "label": label,
            "raw_label": "",
            "has_real_data": True,
            "metrics": metrics,
            "eval_summary": delta,
            "artifacts": [],
        })

    (ckpt / "tree.json").write_text(json.dumps({
        "run_id": run_id,
        "experiment_goal": "Optimise SpMM throughput on CPU",
        "nodes": nodes_dict,
    }))

    if with_uploads:
        uploads = ckpt / "uploads"
        uploads.mkdir()
        (uploads / "input_matrix.csv").write_text("row,col,val\n1,1,0.5\n")

    if with_figures:
        (ckpt / "fig_throughput.pdf").write_bytes(b"%PDF-1.4 fake\n")
        (ckpt / "fig_breakdown.png").write_bytes(b"\x89PNG\r\n\x1a\nfake")

    if with_publish_license:
        ear = ckpt / "ear"
        ear.mkdir()
        (ear / "publish.yaml").write_text(
            yaml.safe_dump({"license": with_publish_license}))

    return ckpt


# ── T-C1: code/<node_id>/ no longer created ─────────────────────────────


def test_TC1_code_subdir_per_node_is_absent(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    code_dir = ckpt / "ear" / "code"
    assert code_dir.is_dir()
    # No path under code/ may begin with the legacy "node_<id>" pattern.
    for p in code_dir.rglob("*"):
        rel = str(p.relative_to(code_dir))
        assert not rel.startswith("node_"), f"legacy code/{rel} should not exist"


# ── T-C2: code/ files are byte-equal to their from_node_id work_dir ─────


def test_TC2_code_files_byte_equal_to_origin(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    prov = json.loads((ckpt / "_provenance.json").read_text())
    assert prov["files"], "provenance should record at least one code file"
    workspace = ckpt.parent.parent
    run_id = ckpt.name
    for rec in prov["files"]:
        dest = ckpt / rec["dest"]
        # dest is `ear/code/<rel>`; strip the `ear/code/` prefix to get the
        # work_dir-relative path of the source file.
        rel = Path(rec["dest"]).relative_to("ear/code")
        src = workspace / "experiments" / run_id / rec["from_node_id"] / rel
        assert dest.is_file(), rec
        assert src.is_file(), rec
        assert _sha256(dest) == _sha256(src), (
            f"byte mismatch for {rec['dest']} vs {src}")


# ── T-C3: from_node_id matches files_changed chain ──────────────────────


def test_TC3_from_node_id_matches_contributing_chain(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    prov = json.loads((ckpt / "_provenance.json").read_text())
    by_dest = {r["dest"]: r["from_node_id"] for r in prov["files"]}
    # Deepest contributor wins: improve modifies main.cpp + run_job.sh and
    # adds tiling.h. Validation contributes nothing.
    assert by_dest["ear/code/main.cpp"] == "node_improve"
    assert by_dest["ear/code/run_job.sh"] == "node_improve"
    assert by_dest["ear/code/tiling.h"] == "node_improve"
    # No file should be attributed to the validation node (it didn't add or
    # modify anything).
    assert "node_validation" not in by_dest.values()


# ── T-C4: validation node is in excluded_nodes ──────────────────────────


def test_TC4_non_contributing_node_in_excluded(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    prov = json.loads((ckpt / "_provenance.json").read_text())
    # always_include keeps best in the chain, so validation is NOT in
    # excluded_nodes — the spec calls this out as a feature. Other
    # non-contributing nodes (none in this fixture) would be excluded.
    excluded_ids = {e["node_id"] for e in prov["excluded_nodes"]}
    assert "node_validation" not in excluded_ids


def test_TC4b_validation_only_chain_records_validation_in_provenance(
    tmp_path: Path,
):
    """When the validation node IS the best, the chain still includes it."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    prov = json.loads((ckpt / "_provenance.json").read_text())
    # The chain depth should equal 3 (draft → improve → validation).
    # And the best node id is the validation node.
    assert prov["best_node_id"] == "node_validation"


# ── T-C5: best is always retained ───────────────────────────────────────


def test_TC5_best_is_always_included(tmp_path: Path):
    """The validation node has empty files_changed — but as best it survives
    the for_code filter via always_include and the chain depth reflects it."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    out = fn(str(ckpt))
    assert out["top_node_id"] == "node_validation"
    assert out["best_chain_depth"] == 3


# ── T-C6: data/ mirrors uploads/ verbatim ───────────────────────────────


def test_TC6_data_mirrors_uploads_no_subdir(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_uploads=True)
    fn = _get_generate_ear()
    fn(str(ckpt))
    data = ckpt / "ear" / "data"
    assert data.is_dir()
    assert (data / "input_matrix.csv").is_file()
    # No "inputs/" subdirectory wrapper.
    assert not (data / "inputs").exists()


def test_TC6b_data_dir_absent_when_uploads_empty(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_uploads=False)
    fn = _get_generate_ear()
    fn(str(ckpt))
    data = ckpt / "ear" / "data"
    assert not data.exists()


# ── T-C7: experiment outputs are NOT bundled into ear/ ──────────────────


def test_TC7_experiment_outputs_not_in_ear(tmp_path: Path):
    """The fake nodes' run_job.sh references `result.csv`. The CSV is not
    actually written (since we don't run the script) so we add a synthetic
    CSV to the best work_dir and verify it is NOT mirrored anywhere under
    ear/ — outputs must be regenerated, never published."""
    ckpt = _make_chain_checkpoint(tmp_path)
    workspace = ckpt.parent.parent
    run_id = ckpt.name
    best_wd = workspace / "experiments" / run_id / "node_validation"
    (best_wd / "result.csv").write_text("k,v\n1,42\n")
    (best_wd / "log.txt").write_text("done\n")

    fn = _get_generate_ear()
    fn(str(ckpt))
    ear = ckpt / "ear"
    found_csv = list(ear.rglob("result.csv"))
    found_log = list(ear.rglob("log.txt"))
    assert found_csv == [], f"experiment output leaked into ear/: {found_csv}"
    assert found_log == [], f"experiment log leaked into ear/: {found_log}"


# ── T-C8: figures/ is top-level (no data/figures) ───────────────────────


def test_TC8_figures_at_top_level(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_figures=True)
    fn = _get_generate_ear()
    fn(str(ckpt))
    ear = ckpt / "ear"
    assert (ear / "figures" / "fig_throughput.pdf").is_file()
    assert (ear / "figures" / "fig_breakdown.png").is_file()
    assert not (ear / "data" / "figures").exists()


# ── T-C9: EVOLUTION.md contains delta_vs_parent and no opaque node ids ──


def test_TC9_evolution_md_uses_step_labels_not_node_ids(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    evo = (ckpt / "EVOLUTION.md").read_text()
    assert "Search trajectory" in evo
    assert "Per-step details" in evo
    # Per-step labels appear.
    assert "draft" in evo
    assert "improve" in evo
    assert "validation" in evo
    # Each contributing node's delta_vs_parent appears verbatim.
    assert "Initial naïve baseline" in evo
    assert "loop tiling" in evo
    assert "Re-ran with 5 seeds" in evo
    # Opaque internal identifiers must NOT appear.
    assert "node_draft" not in evo
    assert "node_improve" not in evo
    assert "node_validation" not in evo
    assert "depth_in_chain" not in evo
    assert "excluded_nodes" not in evo.lower()


# ── T-C10: reproduce.sh contains the best report's literal commands ─────


def test_TC10_reproduce_sh_inlines_best_report_commands(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    repro = (ckpt / "ear" / "reproduce.sh").read_text()
    assert "g++ -O3 main.cpp -o main" in repro
    assert "./main --out result.csv" in repro
    # Also has the safety preamble.
    assert "set -euo pipefail" in repro


def test_render_reproduce_sh_falls_back_to_run_job_wrapper(tmp_path: Path):
    """Bug 3b safety net: when node_report's build/run extraction degenerated
    to env-var-only lines (e.g. ``CXX=g++``), `_render_reproduce_sh` should
    fall back to wrapping ``code/run_job.sh`` so the EAR's reproduce.sh
    actually executes something."""
    import importlib
    transform_src = (
        Path(__file__).parent.parent.parent / "ari-skill-transform" / "src"
    ).resolve()
    if str(transform_src) not in sys.path:
        sys.path.insert(0, str(transform_src))
    server = importlib.import_module("server")

    code_dir = tmp_path / "code"
    code_dir.mkdir()
    (code_dir / "run_job.sh").write_text(
        "#!/usr/bin/env bash\n"
        "$CXX $CXXFLAGS spmm.cpp -o spmm\n"
        "./spmm --m 1000\n"
    )
    bad_report = {
        "build_command": "CXX=${CXX:-g++}",
        "run_command": 'CXXFLAGS="-O3 -march=native"',
    }
    body = server._render_reproduce_sh(bad_report, code_dir=code_dir)
    assert body is not None
    assert body.startswith("#!/usr/bin/env bash")
    assert "set -euo pipefail" in body
    # The fallback wrapper should invoke run_job.sh, not embed the env-only
    # build/run lines.
    assert "bash run_job.sh" in body
    assert "fallback wrapper" in body
    # It must NOT contain the bare env-var lines as commands.
    assert "CXX=${CXX:-g++}\n\n\n" not in body  # no orphaned env-only line
    # A1: must promote per-run output artifacts from code/ up to repo root
    # so rubric's expected_artifacts (repo-relative paths) can match them.
    assert "*.csv" in body and "*.pdf" in body
    assert 'cp -f "$_f" "../$_f"' in body


def test_render_reproduce_sh_keeps_substantive_build_run(tmp_path: Path):
    """When node_report's build/run extraction succeeded, prefer the literal
    commands over the wrapper fallback."""
    import importlib
    transform_src = (
        Path(__file__).parent.parent.parent / "ari-skill-transform" / "src"
    ).resolve()
    if str(transform_src) not in sys.path:
        sys.path.insert(0, str(transform_src))
    server = importlib.import_module("server")

    code_dir = tmp_path / "code"
    code_dir.mkdir()
    (code_dir / "run_job.sh").write_text("#!/usr/bin/env bash\necho should-not-be-used\n")
    good_report = {
        "build_command": "g++ -O3 main.cpp -o main",
        "run_command": "./main --out result.csv",
    }
    body = server._render_reproduce_sh(good_report, code_dir=code_dir)
    assert "g++ -O3 main.cpp -o main" in body
    assert "./main --out result.csv" in body
    assert "fallback wrapper" not in body
    assert "bash run_job.sh" not in body


# ── T-C11: README.md surfaces optional architecture section ─────────────


def test_TC11_architecture_section_optional(tmp_path: Path):
    """When science_data.json has implementation_overview.architecture, README
    shows it; when absent, no Architecture section appears."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    readme1 = (ckpt / "ear" / "README.md").read_text()
    assert "## Architecture" not in readme1

    # Now add an implementation_overview and re-run.
    (ckpt / "science_data.json").write_text(json.dumps({
        "implementation_overview": {
            "architecture": "Three-loop CSR with k-tile blocking and OpenMP.",
            "key_algorithms": [],
        },
    }))
    fn(str(ckpt))
    readme2 = (ckpt / "ear" / "README.md").read_text()
    assert "## Architecture" in readme2
    assert "Three-loop CSR with k-tile blocking" in readme2


# ── T-C12: report-absent fallback (workdir scan) ────────────────────────


def test_TC12_fallback_to_workdir_scan_when_no_reports(tmp_path: Path):
    """If no node_report.json exists for any node, generate_ear falls back
    to a whitelist scan of the best node's work_dir."""
    ckpt = _make_chain_checkpoint(tmp_path)
    # Wipe every node_report.json.
    workspace = ckpt.parent.parent
    run_id = ckpt.name
    for nr_file in (workspace / "experiments" / run_id).rglob("node_report.json"):
        nr_file.unlink()

    fn = _get_generate_ear()
    out = fn(str(ckpt))
    assert out["code_layout"] == "fallback_workdir_scan"
    assert out["top_node_id"] == "node_validation"
    code_dir = ckpt / "ear" / "code"
    # validation work_dir holds the inherited files.
    assert (code_dir / "main.cpp").is_file()
    assert (code_dir / "tiling.h").is_file()


# ── T-C13: _provenance.json schema ──────────────────────────────────────


def test_TC13_provenance_schema(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_uploads=True, with_figures=True)
    fn = _get_generate_ear()
    fn(str(ckpt))
    prov = json.loads((ckpt / "_provenance.json").read_text())

    assert prov["schema_version"] == 1
    assert prov["best_node_id"] == "node_validation"
    assert prov["method"] in {"node_report", "fallback_workdir_scan"}
    # files: each has dest, from_node_id, introduced_by, depth_in_chain, size.
    # Paths are checkpoint-relative since _provenance.json now lives at
    # checkpoint root, so files under ear/ are recorded as `ear/...`.
    assert prov["files"]
    for rec in prov["files"]:
        assert rec["dest"].startswith("ear/code/")
        assert rec["from_node_id"]
        assert rec["introduced_by"] in {"added", "modified", "fallback_workdir_scan"}
        assert "depth_in_chain" in rec
        assert "size" in rec
        # No absolute paths and no sha256 in provenance (manifest.lock owns that).
        assert "/tmp" not in rec.get("dest", "")
        assert "sha256" not in rec
    # data records.
    assert any(d["dest"].startswith("ear/data/") for d in prov["data"])
    # figures records.
    assert any(f["dest"].startswith("ear/figures/") for f in prov["figures"])
    # rendered records mention deterministic_render only.
    for r in prov["rendered"]:
        assert r["method"] == "deterministic_render"
    assert "excluded_nodes" in prov
    assert "warnings" in prov


# ── T-C14: legacy outputs are not generated ─────────────────────────────


def test_TC14_legacy_internal_metadata_not_emitted(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    ear = ckpt / "ear"
    # None of these should exist.
    forbidden = [
        "logs",
        "reproducibility",
        "RESULTS.md",
        "data/raw_metrics.json",
        "data/science_data.json",
        "data/figures",
        "logs/bfts_tree.json",
        "logs/eval_scores.json",
        "reproducibility/commands.md",
        "reproducibility/run_config.json",
        "reproducibility/environment.json",
    ]
    for rel in forbidden:
        p = ear / rel
        assert not p.exists(), f"forbidden artefact present: {rel}"


def test_TC14b_no_internal_meta_files_anywhere_under_ear(tmp_path: Path):
    """Belt-and-braces: NFR-9 contract."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    ear = ckpt / "ear"
    forbidden_names = {
        "tree.json", "nodes_tree.json", "bfts_tree.json",
        "science_data.json", "raw_metrics.json", "eval_scores.json",
        "node_report.json", "cost_trace.jsonl",
        "memory_access.jsonl", "viz_access.jsonl",
        "commands.md",
        # ARI audit logs live at checkpoint root, never under ear/.
        "EVOLUTION.md", "_provenance.json",
    }
    found = [str(p.relative_to(ear)) for p in ear.rglob("*")
             if p.is_file() and p.name in forbidden_names]
    assert found == [], f"internal meta leaked into ear/: {found}"


def test_audit_logs_at_checkpoint_root_not_in_ear(tmp_path: Path):
    """EVOLUTION.md and _provenance.json are checkpoint-root audit logs."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    ear = ckpt / "ear"
    # Present at checkpoint root.
    assert (ckpt / "EVOLUTION.md").is_file()
    assert (ckpt / "_provenance.json").is_file()
    # Absent under ear/.
    assert not (ear / "EVOLUTION.md").exists()
    assert not (ear / "_provenance.json").exists()


def test_audit_logs_replace_legacy_ear_copies_on_regenerate(tmp_path: Path):
    """A v0.7.0 layout that wrote audit logs under ear/ is migrated cleanly."""
    ckpt = _make_chain_checkpoint(tmp_path)
    ear = ckpt / "ear"
    ear.mkdir(exist_ok=True)
    (ear / "EVOLUTION.md").write_text("legacy")
    (ear / "_provenance.json").write_text("{}")
    fn = _get_generate_ear()
    fn(str(ckpt))
    assert not (ear / "EVOLUTION.md").exists()
    assert not (ear / "_provenance.json").exists()
    assert (ckpt / "EVOLUTION.md").is_file()
    assert (ckpt / "_provenance.json").is_file()


# ── T-C15: idempotent re-run ────────────────────────────────────────────


def test_TC15_generate_ear_is_idempotent(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_uploads=True, with_figures=True)
    fn = _get_generate_ear()
    fn(str(ckpt))
    snap1 = {p.relative_to(ckpt / "ear"): _sha256(p)
             for p in (ckpt / "ear").rglob("*") if p.is_file()}
    fn(str(ckpt))
    snap2 = {p.relative_to(ckpt / "ear"): _sha256(p)
             for p in (ckpt / "ear").rglob("*") if p.is_file()}
    # All keys should match.
    assert set(snap1.keys()) == set(snap2.keys())
    # All bytes match for "verbatim" files.
    for k in snap1:
        if str(k).startswith("code/") or str(k).startswith("data/") \
                or str(k).startswith("figures/"):
            assert snap1[k] == snap2[k], f"{k} differs across re-runs"


# ── T-C16: legacy-layout → new-layout migration via re-generate ─────────


def test_TC16_old_layout_is_replaced_on_regenerate(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    # Pre-seed a v0.6.0-style layout.
    ear = ckpt / "ear"
    ear.mkdir()
    (ear / "logs").mkdir()
    (ear / "logs" / "bfts_tree.json").write_text("{}")
    (ear / "reproducibility").mkdir()
    (ear / "reproducibility" / "commands.md").write_text("# legacy")
    (ear / "RESULTS.md").write_text("legacy results")
    fn = _get_generate_ear()
    fn(str(ckpt))
    assert not (ear / "logs").exists()
    assert not (ear / "reproducibility").exists()
    assert not (ear / "RESULTS.md").exists()
    assert (ear / "README.md").is_file()


# ── T-C17, T-C18: LICENSE handling ──────────────────────────────────────


def test_TC17_license_emitted_from_spdx(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_publish_license="MIT")
    fn = _get_generate_ear()
    out = fn(str(ckpt))
    assert out["has_license"] is True
    text = (ckpt / "ear" / "LICENSE").read_text()
    assert "MIT License" in text


def test_TC17b_unknown_spdx_yields_no_license(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_publish_license="WTFPL-2.0")
    fn = _get_generate_ear()
    out = fn(str(ckpt))
    assert out["has_license"] is False
    assert not (ckpt / "ear" / "LICENSE").exists()


def test_TC18_existing_author_written_license_is_preserved(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path, with_publish_license="MIT")
    ear = ckpt / "ear"  # already created by _make_chain_checkpoint via publish.yaml
    (ear / "LICENSE").write_text("AUTHOR HAND-WRITTEN")
    fn = _get_generate_ear()
    fn(str(ckpt))
    assert (ear / "LICENSE").read_text() == "AUTHOR HAND-WRITTEN"


# ── existing-API stability ──────────────────────────────────────────────


def test_generate_ear_returns_top_node_id(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    out = fn(str(ckpt))
    assert out["top_node_id"] == "node_validation"


def test_generate_ear_missing_checkpoint(tmp_path: Path):
    fn = _get_generate_ear()
    result = fn(str(tmp_path / "does_not_exist"))
    assert "error" in result


def test_environment_json_at_top_level(tmp_path: Path):
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    env_path = ckpt / "ear" / "environment.json"
    assert env_path.is_file()
    env = json.loads(env_path.read_text())
    assert "python_version" in env
    assert "platform" in env
    assert "cpu_count" in env


def test_run_config_moved_to_checkpoint_root(tmp_path: Path):
    """run_config.json now lives at checkpoint root."""
    ckpt = _make_chain_checkpoint(tmp_path)
    fn = _get_generate_ear()
    fn(str(ckpt))
    cfg_root = ckpt / "run_config.json"
    cfg_legacy = ckpt / "ear" / "reproducibility" / "run_config.json"
    assert cfg_root.is_file()
    assert not cfg_legacy.exists()
    cfg = json.loads(cfg_root.read_text())
    assert cfg["top_node_id"] == "node_validation"
    assert cfg["experiment_goal"] == "Optimise SpMM throughput on CPU"


# ── GUI endpoint stability ──────────────────────────────────────────────


def test_api_ear_endpoint_structure(tmp_path: Path, monkeypatch):
    ckpt = _make_chain_checkpoint(tmp_path, with_uploads=True, with_figures=True)
    fn = _get_generate_ear()
    fn(str(ckpt))

    from ari.viz import api_state

    monkeypatch.setattr(
        api_state, "_resolve_checkpoint_dir", lambda run_id: ckpt
    )

    out = api_state._api_ear("test_run")
    assert "error" not in out, out
    assert out["readme"]
    # `results` falls back to checkpoint-root EVOLUTION.md when RESULTS.md
    # is absent under ear/.
    assert out["results"]
    files = {f["path"] for f in out["files"]}
    assert "README.md" in files
    assert "environment.json" in files
    # Audit logs live at checkpoint root, NOT under ear/, so they must not
    # appear in the GUI's ear file listing.
    assert "EVOLUTION.md" not in files
    assert "_provenance.json" not in files
    assert out["file_count"] >= 3


def test_api_ear_endpoint_no_checkpoint(monkeypatch):
    from ari.viz import api_state

    monkeypatch.setattr(api_state, "_resolve_checkpoint_dir", lambda run_id: None)
    out = api_state._api_ear("missing")
    assert out.get("error")


def test_api_ear_endpoint_no_ear_dir(tmp_path: Path, monkeypatch):
    from ari.viz import api_state

    ckpt = tmp_path / "ckpt"
    ckpt.mkdir()
    monkeypatch.setattr(api_state, "_resolve_checkpoint_dir", lambda run_id: ckpt)
    out = api_state._api_ear("ckpt")
    assert out.get("error")


# ── pipeline integration ────────────────────────────────────────────────


def test_workflow_yaml_runs_generate_ear_before_write_paper():
    wf_path = Path(__file__).parent.parent / "config" / "workflow.yaml"
    data = yaml.safe_load(wf_path.read_text())
    pipeline = data.get("pipeline", [])
    stage_order = [s.get("stage", "") for s in pipeline]
    assert "generate_ear" in stage_order
    assert "write_paper" in stage_order
    assert stage_order.index("generate_ear") < stage_order.index("write_paper")


def test_workflow_yaml_generate_ear_uses_transform_skill():
    wf_path = Path(__file__).parent.parent / "config" / "workflow.yaml"
    data = yaml.safe_load(wf_path.read_text())
    stage = next(
        s for s in data.get("pipeline", []) if s.get("stage") == "generate_ear"
    )
    assert stage.get("skill") == "transform-skill"
    assert stage.get("tool") == "generate_ear"
