// @vitest-environment node
/// <reference types="vite/client" />
//
// v1 generated-types drift guard (gui_refresh Wave 2b task 03).
//
// src/services/api/v1types.gen.ts is COMMITTED to the tree (so builds and
// typecheck never depend on codegen running first) and produced by
// `npm run gen:v1types` from ari/viz/v1/openapi.json — which is itself
// generated deterministically from the backend router/DTOs (see
// `python -m ari.viz.v1.openapi --update`).
//
// This test is the chosen drift mechanism (openapi-typescript's JS API runs
// fine under vitest's node environment — no package.json "pretest" hook is
// needed): it regenerates the types in-memory via the openapi-typescript JS
// API, prepends the CLI banner (the CLI adds it; the JS API does not), and
// asserts byte equality with the committed file. If it fails, someone changed
// openapi.json (or bumped openapi-typescript) without rerunning
// `npm run gen:v1types`.
//
// Both inputs are loaded via Vite `?raw` imports (typed by the vite/client
// reference above) instead of node:fs, because the app tsconfig has no
// @types/node — adding it globally would perturb DOM-lib type resolution.
//
// NOTE: this file is intentionally `.test.ts` (no JSX, node environment);
// vitest.config.ts includes `.test.ts` alongside `.test.tsx` for it.

import { describe, it, expect } from 'vitest';
// eslint-disable-next-line import/no-relative-packages -- schema lives one dir above the frontend root by design (ari/viz/v1)
import openapiJsonRaw from '../../../v1/openapi.json?raw';
import committed from '../services/api/v1types.gen.ts?raw';

// Banner the openapi-typescript CLI prepends to -o output. astToString() does
// not emit it, so the regenerated string must be prefixed with it to match the
// committed file byte-for-byte.
const CLI_BANNER =
  '/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n';

describe('v1types.gen.ts drift guard', () => {
  it('committed v1types.gen.ts matches regeneration from ../v1/openapi.json', async () => {
    const { default: openapiTS, astToString } = await import('openapi-typescript');
    const ast = await openapiTS(JSON.parse(openapiJsonRaw));
    const regenerated = CLI_BANNER + astToString(ast);
    expect(
      committed,
      'src/services/api/v1types.gen.ts is stale — run `npm run gen:v1types` after changing ari/viz/v1/openapi.json',
    ).toBe(regenerated);
  });
});
