#!/usr/bin/env python3
"""Auto-generate report tables T2 (skill x role) and T3 (env vars) from
implementation source.

T2: read every ari-skill-* skill.yaml and produce shared/tables/T02_skills.tex
T3: read ari-core/ari/public/config_schema.py and produce shared/tables/T03_envvars.tex

Both files start with a header `% AUTOGENERATED by scripts/build_tables.py — DO NOT EDIT`.
CI runs `make tables` then `git diff --exit-code` to detect drift.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPORT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = REPORT_ROOT.parent
TABLES = REPORT_ROOT / "shared" / "tables"

HEADER = "% AUTOGENERATED by scripts/build_tables.py — DO NOT EDIT\n"


def _escape_tex(s: str) -> str:
    return (s.replace("\\", "\\textbackslash{}")
             .replace("&", r"\&")
             .replace("%", r"\%")
             .replace("_", r"\_")
             .replace("#", r"\#")
             .replace("$", r"\$"))


def build_t02_skills() -> Path:
    rows = []
    for d in sorted(REPO_ROOT.glob("ari-skill-*")):
        cfg = d / "skill.yaml"
        if not cfg.exists():
            continue
        try:
            data = yaml.safe_load(cfg.read_text(encoding="utf-8"))
        except yaml.YAMLError:
            continue
        name = data.get("name") or d.name.removeprefix("ari-skill-")
        desc = (data.get("description") or "").splitlines()[0][:80]
        rows.append((name, desc))
    TABLES.mkdir(parents=True, exist_ok=True)
    out = TABLES / "T02_skills.tex"
    body = (
        HEADER
        + "\\begin{longtable}{@{}p{0.22\\linewidth}p{0.72\\linewidth}@{}}\n"
        + "  \\toprule\n  Skill & Description \\\\\n  \\midrule\n  \\endhead\n"
        + "".join(f"  \\texttt{{{_escape_tex(n)}}} & {_escape_tex(d)} \\\\\n" for n, d in rows)
        + "  \\bottomrule\n\\end{longtable}\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def build_t03_envvars() -> Path:
    schema = REPO_ROOT / "ari-core" / "ari" / "public" / "config_schema.py"
    if not schema.exists():
        return TABLES / "T03_envvars.tex"
    text = schema.read_text(encoding="utf-8")
    rows = []
    for m in re.finditer(r'"(ARI_[A-Z0-9_]+)"\s*:\s*\{[^}]*?"description"\s*:\s*"([^"]*)"', text, re.DOTALL):
        rows.append((m.group(1), m.group(2)[:90]))
    if not rows:
        # fallback: extract all ARI_* tokens with no description
        for name in sorted(set(re.findall(r"ARI_[A-Z0-9_]+", text))):
            rows.append((name, ""))
    TABLES.mkdir(parents=True, exist_ok=True)
    out = TABLES / "T03_envvars.tex"
    body = (
        HEADER
        + "\\begin{longtable}{@{}p{0.30\\linewidth}p{0.65\\linewidth}@{}}\n"
        + "  \\toprule\n  Variable & Description \\\\\n  \\midrule\n  \\endhead\n"
        + "".join(f"  \\texttt{{{_escape_tex(n)}}} & {_escape_tex(d)} \\\\\n" for n, d in rows)
        + "  \\bottomrule\n\\end{longtable}\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> int:
    p2 = build_t02_skills()
    p3 = build_t03_envvars()
    print(f"[build_tables] wrote {p2.name}, {p3.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
