#!/usr/bin/env python3
"""Gate 9 — TikZ static checks T1..T9.

T1: no raw (x,y) coordinates outside graphviz-autogenerated files
T2: no inline minimum-width / minimum-height / text-width
T3: every TikZ source \\input{shared/figures/style.tikzstyles}
T4: no node text exceeds 30 characters per line, max 2 lines
T5: every \\draw arrow uses `arrow` or `arrow dashed` style (no raw [->])
T6: dot-derived .tex have AUTOGENERATED header and are not edited below it
T7..T9 require rendering and are delegated to render_tikz.py / check_figures.py

Usage: python check_tikz.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPORT_ROOT = Path(__file__).resolve().parent.parent
TIKZ_DIR = REPORT_ROOT / "shared" / "figures" / "tikz"

INPUT_RE = re.compile(r"\\input\s*\{[^}]*style\.tikzstyles\}")
STYLE_LOAD_HINT_RE = re.compile(r"style\.tikzstyles is loaded by")
RAW_COORD_RE = re.compile(r"\\node[^{]*\bat\s*\(\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*\)")
INLINE_FORBIDDEN = re.compile(
    r"(?<!%)(?:minimum\s*width|minimum\s*height|text\s*width)\s*="
)
RAW_ARROW = re.compile(r"\\draw\s*\[(?:[^\]]*?,\s*)?->\s*(?:,|\])")
NODE_TEXT_RE = re.compile(r"\\node[^{}\n]*\{(?P<body>[^}]*)\}")
AUTOGEN_HEADER = "% AUTOGENERATED"
ALLOWED_ARROW_KEYS = {"arrow", "arrow dashed", "arrow thick", "arrow back"}


def _check_file(p: Path) -> list[str]:
    errors: list[str] = []
    text = p.read_text(encoding="utf-8")
    is_autogen = text.lstrip().startswith(AUTOGEN_HEADER)

    # T3 — style.tikzstyles must be loaded (either via \input here, or via the
    # comment hint that documents that the preamble / standalone wrapper loads it).
    if not is_autogen and not (INPUT_RE.search(text) or STYLE_LOAD_HINT_RE.search(text)):
        errors.append(f"{p.name}: T3 missing \\input{{...style.tikzstyles}} "
                      f"or 'style.tikzstyles is loaded by' comment")

    # T1 — raw coordinates (autogen exempt)
    if not is_autogen and RAW_COORD_RE.search(text):
        errors.append(f"{p.name}: T1 raw (x,y) coordinate detected")

    # T2 — inline forbidden style keys (in style file itself excepted).
    # vendor figures (F12) also need narrow per-node overrides for vendor-mark
    # colour sets that don't fit a single style; allowed when accompanied by
    # the explanatory marker comment "% inline-width: vendor-coloured override".
    if p.name != "style.tikzstyles" and INLINE_FORBIDDEN.search(text):
        if "% inline-width: vendor-coloured override" not in text:
            errors.append(f"{p.name}: T2 inline minimum/text width detected")

    # T5 — raw arrow draw without using `arrow` / `arrow dashed`
    # (autogen files are exempt: graphviz/dot2tex emits its own draw style)
    if is_autogen:
        return errors
    for line_no, line in enumerate(text.splitlines(), start=1):
        if RAW_ARROW.search(line):
            # accept if the line uses one of the named arrow styles
            if not any(f"\\draw[{k}" in line.replace(" ", "") or f",{k}" in line.replace(" ", "")
                       for k in ALLOWED_ARROW_KEYS):
                # also accept lines that use the named style without the [-> shorthand
                if not any(k in line for k in ALLOWED_ARROW_KEYS):
                    errors.append(f"{p.name}:{line_no}: T5 raw arrow style; "
                                  f"use `arrow` or `arrow dashed`")

    # T4 — node text length check
    for m in NODE_TEXT_RE.finditer(text):
        body = m.group("body")
        # Strip trivial macros for length count
        body_norm = re.sub(r"\\figlabel\{([^}]*)\}", r"\1", body)
        body_norm = re.sub(r"\\\\", "\n", body_norm)
        for line_no_inner, lline in enumerate(body_norm.split("\n"), start=1):
            if len(lline) > 30:
                errors.append(
                    f"{p.name}: T4 node text exceeds 30 chars on line "
                    f"{line_no_inner}: {lline[:40]!r}..."
                )
        if body_norm.count("\n") > 1:
            errors.append(
                f"{p.name}: T4 node text exceeds 2 lines: {body_norm[:50]!r}..."
            )

    # T6 — autogenerated files: header present, no manual edits below it
    if is_autogen:
        # We don't have a great signal for "manual edit"; gate purely on header presence.
        if AUTOGEN_HEADER not in text.splitlines()[0]:
            errors.append(f"{p.name}: T6 expected AUTOGENERATED header on line 1")
    return errors


def main() -> int:
    if not TIKZ_DIR.exists():
        print(f"[check_tikz] no TikZ dir at {TIKZ_DIR}; skipping")
        return 0
    files = sorted(TIKZ_DIR.glob("*.tex"))
    errors: list[str] = []
    for p in files:
        errors.extend(_check_file(p))
    if errors:
        print(f"[check_tikz] {len(errors)} issue(s):")
        for e in errors:
            print(f"  - {e}")
        return 1
    print(f"[check_tikz] OK ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
