#!/usr/bin/env python3
"""Gate R1..R10 — figure quality checks.

R1  PDF has no raster image  (per PDF, post-build)
R2  grayscale-distinguishable (skipped here — needs PDF render)
R3  font matches body         (skipped — heuristic)
R4  min font ≥ 7pt            (skipped — render-time)
R5  naming F<NN>_<slug>       (file name regex)
R6  i18n via \\figlabel{}      (string scan)
R7  caption present in en/ja/zh chapters (parsed from chapter sources)
R8  data-driven figs have *.meta.yaml
R9  figures reproducible      (delegated to `make figures && git diff --exit-code`)
R10 alt text in HTML          (post-html)

This script implements R5, R6, R8 statically; R1..R4 / R10 require build artifacts.
With `--render-all` it forwards every TikZ source to render_tikz.py for T7..T9.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPORT_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPORT_ROOT / "shared"
TIKZ_DIR = SHARED / "figures" / "tikz"
PGF_DIR = SHARED / "figures" / "pgf"
DATA_DIR = SHARED / "figures" / "data"
NAME_RE = re.compile(r"^[FT]\d{2}_[a-z0-9_]+$")
LABEL_RE = re.compile(r"\\label\{(?:fig|tab):([a-z0-9_]+)\}")
DIRECT_TEXT_RE = re.compile(r"\\node[^{]*\{([^{}\\]+)\}")
DATA_DRIVEN_PREFIX = ("F02", "F07", "F08", "F09")
# Matches the boolean flag `synthetic: true` (not `raw_source: synthetic`).
SYNTHETIC_RE = re.compile(r"^\s*synthetic:\s*true\b", re.MULTILINE)
# Data-driven figures whose meta declares synthetic data are tolerated ONLY if
# listed here — an explicit, reviewed acknowledgement that the figure is
# illustrative (and should carry an in-figure "illustrative" marker). Any new
# synthetic figure, or one that regresses from real to synthetic data, fails
# R8 until it is consciously added, instead of shipping silently as if real.
SYNTHETIC_ALLOWLIST = {"F02", "F07", "F08", "F09"}


def _r5_naming() -> list[str]:
    errors = []
    for d in (TIKZ_DIR, PGF_DIR):
        if not d.exists():
            continue
        for p in d.iterdir():
            # Underscore-prefixed .tex files are shared style includes
            # (e.g. tikz/_style.tex), not figures; R5 applies to figures only.
            if p.stem.startswith("_"):
                continue
            if p.is_file() and not NAME_RE.match(p.stem):
                errors.append(f"R5 naming violation: {p.relative_to(REPORT_ROOT)}")
    return errors


def _r6_figlabel() -> list[str]:
    errors = []
    if not TIKZ_DIR.exists():
        return errors
    for p in TIKZ_DIR.glob("*.tex"):
        text = p.read_text(encoding="utf-8")
        if text.lstrip().startswith("% AUTOGENERATED"):
            continue
        # Bypass: text inside math (begins with $) or numeric-only labels
        for m in DIRECT_TEXT_RE.finditer(text):
            body = m.group(1).strip()
            if not body:
                continue
            if body.startswith("$") and body.endswith("$"):
                continue
            if re.fullmatch(r"[0-9]+\.?[0-9]*", body):
                continue
            if "\\figlabel" in body or "\\input" in body:
                continue
            # Empty wrappers like { } caught by .strip
            errors.append(f"R6 raw node text in {p.name}: {body!r}")
    return errors


def _r8_meta() -> tuple[list[str], list[str]]:
    """R8 — data-driven figures must carry a meta.yaml, and any meta that
    declares `synthetic: true` must be explicitly allowlisted (so synthetic
    data cannot silently ship as if it were empirical). Returns (errors, notes)."""
    errors: list[str] = []
    notes: list[str] = []
    if not DATA_DIR.exists():
        return errors, notes
    seen = {p.stem.split(".")[0] for p in DATA_DIR.iterdir() if p.is_file()}
    for prefix in DATA_DRIVEN_PREFIX:
        matches = [s for s in seen if s.startswith(prefix)]
        metas = [DATA_DIR / f"{m}.meta.yaml" for m in matches
                 if (DATA_DIR / f"{m}.meta.yaml").exists()]
        if matches and not metas:
            errors.append(f"R8 data-driven {prefix}_* lacks .meta.yaml")
            continue
        for meta in metas:
            if not SYNTHETIC_RE.search(meta.read_text(encoding="utf-8")):
                continue
            if prefix in SYNTHETIC_ALLOWLIST:
                notes.append(
                    f"R8 {meta.name}: synthetic/illustrative data "
                    f"(allowlisted; replace with a real checkpoint before external citation)"
                )
            else:
                errors.append(
                    f"R8 {meta.name} declares `synthetic: true` but {prefix} is not "
                    f"in SYNTHETIC_ALLOWLIST — supply real data or consciously allowlist it"
                )
    return errors, notes


def _render_all() -> list[str]:
    errors = []
    if not TIKZ_DIR.exists():
        return errors
    rt = REPORT_ROOT / "scripts" / "render_tikz.py"
    for p in sorted(TIKZ_DIR.glob("*.tex")):
        if p.read_text(encoding="utf-8").lstrip().startswith("% AUTOGENERATED"):
            continue
        # Shared style includes (tikz/_style.tex) typeset nothing on their
        # own — rendering them standalone yields an empty PDF; skip.
        if p.stem.startswith("_"):
            continue
        rc = subprocess.call([sys.executable, str(rt), str(p)])
        if rc != 0:
            errors.append(f"render_tikz failed for {p.name}")
    return errors


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render-all", action="store_true",
                    help="Also render every TikZ via render_tikz.py (T7..T9)")
    args = ap.parse_args()

    errors: list[str] = []
    notes: list[str] = []
    errors.extend(_r5_naming())
    errors.extend(_r6_figlabel())
    r8_errors, r8_notes = _r8_meta()
    errors.extend(r8_errors)
    notes.extend(r8_notes)
    if args.render_all:
        errors.extend(_render_all())

    for n in notes:
        print(f"[check_figures] note: {n}")
    if errors:
        print(f"[check_figures] {len(errors)} issue(s):")
        for e in errors:
            print(f"  - {e}")
        return 1
    print("[check_figures] OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
