"""Generic ARI runtime builder — zero domain-specific code.

cli.py only reads arguments and calls this module.
MetricSpec generation is delegated to evaluator-skill and not returned to cli.py.
"""

from __future__ import annotations

import importlib.util
import logging
import os
import re
from pathlib import Path

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# MetricSpec: auto-generated from evaluator-skill
# ---------------------------------------------------------------------------

def _make_metric_spec():
    """Always returns the same generic MetricSpec. Zero domain knowledge.

    Evaluation is autonomously determined by LLMEvaluator from the goal text.
    No branching. No keyword parsing.
    """
    from ari.evaluator import MetricSpec
    import re as _re_num
    _pat = _re_num.compile(r"\b(\d+\.\d+|\d{4,})\b")

    def _generic_extractor(text: str) -> dict:
        nums = [float(x) for x in _pat.findall(text) if float(x) >= 1.0]
        return {"result_" + str(i): v for i, v in enumerate(nums[:20])}

    return MetricSpec(name="generic experiment", artifact_extractor=_generic_extractor)


# ---------------------------------------------------------------------------
# Runtime builder
# ---------------------------------------------------------------------------

def build_runtime(cfg, experiment_text: str = ""):
    """Build and return a generic ARI runtime. No domain-specific code."""
    from ari.agent.loop import AgentLoop
    from ari.agent.workflow import from_experiment_text
    from ari.evaluator import LLMEvaluator
    from ari.llm.client import LLMClient
    from ari.mcp.client import MCPClient
    from ari.memory.file_client import FileMemoryClient
    from ari.orchestrator.bfts import BFTS
    from ari.orchestrator.scheduler import Scheduler

    llm = LLMClient(cfg.llm)
    memory = FileMemoryClient("~/.ari/memory.json")
    mcp = MCPClient(cfg.skills)
    bfts = BFTS(cfg.bfts, llm)

    # MetricSpec: auto-generated from experiment file by evaluator-skill
    metric_spec = _make_metric_spec()

    evaluator = LLMEvaluator(
        model=llm._model_name(),
        api_base=llm.config.base_url if llm.config.backend == "ollama" else None,
        metric_spec=metric_spec,
    )

    # WorkflowHints: auto-extracted from experiment file
    wf_hints = from_experiment_text(experiment_text)

    # metric_extractor: generated by workflow.py from metric_keyword; falls back to MetricSpec extractor
    if wf_hints.metric_extractor is None and metric_spec and metric_spec.artifact_extractor:
        wf_hints.metric_extractor = metric_spec.artifact_extractor

    agent = AgentLoop(llm, memory, mcp, evaluator=evaluator, workflow_hints=wf_hints)
    scheduler = Scheduler(cfg.bfts)
    return llm, memory, mcp, bfts, agent, scheduler, metric_spec


# ---------------------------------------------------------------------------
# Paper section generation (generic)
# ---------------------------------------------------------------------------



# ---------------------------------------------------------------------------
# Post-BFTS pipeline (driven by pipeline.yaml)
# ---------------------------------------------------------------------------

def generate_paper_section(
    all_nodes, experiment_data: dict, checkpoint_dir: Path, mcp, config_path: str
) -> None:
    """Run the post-BFTS pipeline according to pipeline.yaml. No hardcoding."""
    from ari.pipeline import load_pipeline, run_pipeline

    pipeline_yaml_candidates = [
        Path(config_path).parent / "pipeline.yaml",
        Path(__file__).parent.parent / "config" / "pipeline.yaml",
    ]
    pipeline_yaml = next((p for p in pipeline_yaml_candidates if p.exists()), None)

    if pipeline_yaml is None:
        log.warning("pipeline.yaml not found; skipping post-BFTS pipeline")
        return

    stages = load_pipeline(pipeline_yaml)
    if not stages:
        log.info("No enabled pipeline stages in %s", pipeline_yaml)
        return

    log.info(
        "Running post-BFTS pipeline: %d stage(s) from %s",
        len(stages), pipeline_yaml,
    )
    run_pipeline(stages, all_nodes, experiment_data, checkpoint_dir, config_path)
