/* selftest.c — LOCAL accuracy self-test for the erfc task.
 *
 * NOT the evaluator and NOT used for scoring. Reads seeded reference points
 * (ref_points.csv: "x  erfc_ref" per line, provided in your working directory),
 * evaluates your myerfc(x), and reports the per-REGION pass rate (relative error
 * < 1e-9) plus an overall score. The regions need different numerical regimes:
 *   center [-5,2)   mid [2,6)   tail [6,15)   deeptail [15,26)
 *
 * The evaluator uses DIFFERENT (hidden) points, so you cannot pass by hardcoding
 * these — only a genuinely accurate myerfc generalizes. Build & run:
 *     make selftest && ./selftest
 * Do NOT edit this file or call erf/erfc; edit candidate_erfc.c.
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "erfc_kernel.h"

#define TOL 1e-9
#define NREG 4
static const double LO[NREG] = {-5.0, 2.0, 6.0, 15.0};
static const double HI[NREG] = { 2.0, 6.0, 15.0, 26.0};
static const char *NAME[NREG] = {"center", "mid", "tail", "deeptail"};

int main(void) {
    FILE *f = fopen("ref_points.csv", "r");
    if (!f) { fprintf(stderr, "ref_points.csv not found in work dir\n"); return 2; }
    long tot = 0, ok = 0;
    long rtot[NREG] = {0}, rok[NREG] = {0};
    double rmax[NREG] = {0};
    double x, ref;
    while (fscanf(f, "%lf %lf", &x, &ref) == 2) {
        if (!(ref > 0.0)) continue;
        double got = myerfc(x);
        double rel = fabs(got - ref) / fabs(ref);
        int good = isfinite(rel) && rel < TOL;
        tot++; ok += good;
        for (int r = 0; r < NREG; ++r) {
            if (x >= LO[r] && x < HI[r]) {
                rtot[r]++; rok[r] += good;
                if (isfinite(rel) && rel > rmax[r]) rmax[r] = rel;
                break;
            }
        }
    }
    fclose(f);
    printf("erfc self-test (tol=%.0e, %ld points)\n", TOL, tot);
    for (int r = 0; r < NREG; ++r) {
        double frac = rtot[r] ? (100.0 * rok[r] / rtot[r]) : 100.0;
        printf("  %-9s pass %5.1f%%  (max relerr %.1e)\n", NAME[r], frac, rmax[r]);
    }
    double overall = tot ? (100.0 * ok / tot) : 0.0;
    printf("overall: %.1f%% (%ld/%ld within tol)\n", overall, ok, tot);
    if (overall >= 99.0)
        printf("SELFTEST: PASS  (%.1f%% — keep tightening the worst region)\n", overall);
    else
        printf("SELFTEST: PARTIAL  (%.1f%% — improve the lowest-passing region next)\n", overall);
    return overall >= 99.0 ? 0 : 1;
}
