/* selftest.c — LOCAL developer harness for the SpMM task (handoff study B2b).
 *
 * This is NOT the evaluator and NOT used for scoring. It lets the agent run its
 * candidate locally and get the same kind of feedback the evaluator produces:
 *   - correctness vs an internal fp64 reference, using the SAME row-length-scaled
 *     epsilon bound as the evaluator (C * gamma(nnz_row) * (|A| @ |X|));
 *   - an estimated speedup vs the naive reference (the evaluator's baseline is
 *     the same naive algorithm), so a local number tracks the official one.
 *
 * It runs TWO sparsity structures — a uniform matrix and a skewed/heavy-tailed
 * one (most rows sparse, a few rows very dense). The evaluator tests 6 families;
 * the skewed case here catches the common family-specific failures (load
 * imbalance, dense-row index/accumulation bugs) that a uniform-only test misses.
 * It still does NOT cover every family, so a PASS is a strong-but-not-complete
 * predictor — the evaluator (fresh data, 6 families) remains authoritative.
 *
 * Build:  make selftest        Run:  ./selftest
 *
 * Do NOT edit this file; edit candidate_spmm.c. (The harness provides main();
 * selftest links against your spmm() from candidate_spmm.c.)
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <omp.h>
#include "spmm_kernel.h"

/* Read an int from the environment (study parameter), with a default. */
static int env_int(const char *name, int dflt) {
    const char *v = getenv(name);
    if (!v || !*v) return dflt;
    int x = atoi(v);
    return x > 0 ? x : dflt;
}

#define C_EPS 8.0
static const double FP64_U = 1.1102230246251565e-16; /* 2^-53 */

static double now_sec(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec + (double)t.tv_nsec * 1e-9;
}

static double gamma_k(long k) {
    double ku = (double)k * FP64_U;
    return ku >= 1.0 ? INFINITY : ku / (1.0 - ku);
}

/* Internal naive reference (distinct symbol so it links alongside spmm()). */
static void spmm_ref(int n, int m, int k,
                     const int *indptr, const int *indices, const double *values,
                     const double *X, double *Y) {
    (void)m;
    for (int i = 0; i < n; ++i) {
        double *yi = Y + (long)i * k;
        for (int c = 0; c < k; ++c) yi[c] = 0.0;
        for (int p = indptr[i]; p < indptr[i + 1]; ++p) {
            const double a = values[p];
            const double *xj = X + (long)indices[p] * k;
            for (int c = 0; c < k; ++c) yi[c] += a * xj[c];
        }
    }
}

/* Build a reproducible CSR. skewed=0: ~uniform Bernoulli(density) per cell.
 * skewed=1: heavy-tailed row lengths (most rows ~0.3x, ~5% of rows ~15x the
 * base) at roughly the same total nnz — exercises load imbalance / dense rows. */
static long gen_csr(int n, int m, double density, int skewed,
                    int **out_indptr, int **out_indices, double **out_values) {
    int *indptr = malloc((size_t)(n + 1) * sizeof(int));
    int *row_nnz = malloc((size_t)n * sizeof(int));
    double base = density * (double)m;
    long nnz = 0;
    for (int i = 0; i < n; ++i) {
        int rc;
        if (!skewed) {
            rc = 0;
            for (int j = 0; j < m; ++j)
                if ((double)rand() / (double)RAND_MAX < density) rc++;
        } else {
            double f = ((double)rand() / (double)RAND_MAX < 0.05) ? base * 15.0 : base * 0.3;
            rc = (int)f;
        }
        if (rc < 1) rc = 1;
        if (rc > m) rc = m;
        row_nnz[i] = rc;
        nnz += rc;
    }
    indptr[0] = 0;
    for (int i = 0; i < n; ++i) indptr[i + 1] = indptr[i] + row_nnz[i];

    int *indices = malloc((size_t)nnz * sizeof(int));
    double *values = malloc((size_t)nnz * sizeof(double));
    char *mask = malloc((size_t)m);
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < m; ++j) mask[j] = 0;
        int placed = 0, need = row_nnz[i], p = indptr[i];
        while (placed < need) {
            int col = rand() % m;
            if (!mask[col]) { mask[col] = 1; placed++; }
        }
        for (int j = 0; j < m && p < indptr[i + 1]; ++j) {
            if (mask[j]) {
                indices[p] = j;
                values[p] = ((double)rand() / (double)RAND_MAX) * 2.0 - 1.0;
                p++;
            }
        }
    }
    free(mask);
    free(row_nnz);
    *out_indptr = indptr; *out_indices = indices; *out_values = values;
    return nnz;
}

/* Run one structure; print its line; return 1 if correct, 0 if not. Sets *sp. */
static int run_case(const char *name, int n, int m, int k, int skewed,
                    double density, int warmup, int reps, double *sp) {
    int *indptr, *indices; double *values;
    long nnz = gen_csr(n, m, density, skewed, &indptr, &indices, &values);

    double *X = malloc((size_t)m * k * sizeof(double));
    for (long t = 0; t < (long)m * k; ++t)
        X[t] = ((double)rand() / (double)RAND_MAX) * 2.0 - 1.0;
    double *absvalues = malloc((size_t)nnz * sizeof(double));
    for (long p = 0; p < nnz; ++p) absvalues[p] = fabs(values[p]);
    double *absX = malloc((size_t)m * k * sizeof(double));
    for (long t = 0; t < (long)m * k; ++t) absX[t] = fabs(X[t]);

    double *Yref = malloc((size_t)n * k * sizeof(double));
    double *Ycand = malloc((size_t)n * k * sizeof(double));
    double *Ybound = malloc((size_t)n * k * sizeof(double));
    spmm_ref(n, m, k, indptr, indices, values, X, Yref);
    spmm_ref(n, m, k, indptr, indices, absvalues, absX, Ybound);

    for (int w = 0; w < warmup; ++w)
        spmm(n, m, k, indptr, indices, values, X, Ycand);
    double tc = 0.0;
    for (int r = 0; r < reps; ++r) {
        double t0 = now_sec();
        spmm(n, m, k, indptr, indices, values, X, Ycand);
        tc += now_sec() - t0;
    }
    tc /= reps;

    double *Ytmp = malloc((size_t)n * k * sizeof(double));
    double tb = 0.0;
    for (int r = 0; r < reps; ++r) {
        double t0 = now_sec();
        spmm_ref(n, m, k, indptr, indices, values, X, Ytmp);
        tb += now_sec() - t0;
    }
    tb /= reps;
    free(Ytmp);

    int ok = 1;
    double max_rel = 0.0;
    for (int i = 0; i < n; ++i) {
        double g = gamma_k((long)(indptr[i + 1] - indptr[i]));
        for (int c = 0; c < k; ++c) {
            long idx = (long)i * k + c;
            double resid = fabs(Ycand[idx] - Yref[idx]);
            if (resid > C_EPS * g * Ybound[idx]) ok = 0;
            double denom = fabs(Yref[idx]);
            if (denom > 0.0) {
                double rel = resid / denom;
                if (rel > max_rel) max_rel = rel;
            }
        }
    }
    double speedup = (tc > 0.0) ? (tb / tc) : 0.0;
    *sp = speedup;
    printf("  [%-8s] nnz=%ld  candidate_sec=%.5f  baseline_ref_sec=%.5f  "
           "speedup~%.2fx  correct=%s  max_rel=%.2e\n",
           name, nnz, tc, tb, speedup, ok ? "yes" : "NO", max_rel);

    free(indptr); free(indices); free(values);
    free(X); free(absvalues); free(absX);
    free(Yref); free(Ycand); free(Ybound);
    return ok;
}

int main(void) {
    /* Mirror the evaluator's study parameters so the local number tracks the
     * official one: same matrix size and OpenMP thread budget. A tiny matrix on
     * all cores measures ~1x even for a perfect kernel (parallel overhead). */
    const int n = env_int("ARI_SPMM_N", 20000);
    const int m = n;
    const int k = env_int("ARI_SPMM_K", 64);
    const int threads = env_int("ARI_SPMM_THREADS", 16);
    const double density = 0.02;
    const int warmup = 1, reps = 3;
    omp_set_num_threads(threads);
    srand(12345u);

    printf("problem: n=%d m=%d k=%d density=%.3f  omp_threads=%d  (2 structures)\n",
           n, m, k, density, threads);
    double sp_u = 0.0, sp_s = 0.0;
    int ok_u = run_case("uniform", n, m, k, 0, density, warmup, reps, &sp_u);
    int ok_s = run_case("skewed", n, m, k, 1, density, warmup, reps, &sp_s);

    int ok = ok_u && ok_s;
    double worst = sp_u < sp_s ? sp_u : sp_s;
    if (ok)
        printf("SELFTEST: PASS  (correct on both; worst speedup ~%.2fx vs naive baseline)\n",
               worst);
    else
        printf("SELFTEST: FAIL  (incorrect on %s%s%s — a family failing correctness "
               "=> the evaluator scores 0; fix correctness first)\n",
               ok_u ? "" : "uniform", (!ok_u && !ok_s) ? " and " : "",
               ok_s ? "" : "skewed");
    return ok ? 0 : 1;
}
