#!/usr/bin/env bash
# ============================================================================
# setup_env.sh — .env bootstrap
#   * Creates or updates ARI/.env with every env var the program reads.
#   * Prompts interactively for critical API keys (OPENAI/ANTHROPIC/GOOGLE/S2)
#     when they are missing. Keys already present are left untouched.
#   * All non-key variables are written with commented defaults.
# ============================================================================

ENV_FILE="$ARI_ROOT/.env"

echo ""
echo -e "${BOLD}  🐜 $(m setup_env_title)${RESET}"
echo ""

# --- helpers ----------------------------------------------------------------
# Read an existing value for KEY from $ENV_FILE (empty string if missing / unset).
_env_get() {
  local key="$1"
  [ -f "$ENV_FILE" ] || { echo ""; return; }
  local line
  line=$(grep -E "^[[:space:]]*${key}=" "$ENV_FILE" | tail -1 || true)
  [ -z "$line" ] && { echo ""; return; }
  local val="${line#*=}"
  val="${val%\"}"; val="${val#\"}"
  val="${val%\'}"; val="${val#\'}"
  echo "$val"
}

# True if $ENV_FILE already has a non-empty value for KEY.
_env_has() {
  local key="$1"
  local v
  v=$(_env_get "$key")
  [ -n "$v" ]
}

# Append "KEY=VALUE" only if KEY is not already present (commented or not).
_env_append_if_absent() {
  local line="$1"
  local key="${line%%=*}"
  key="${key# }"; key="${key#\#}"; key="${key# }"
  key="${key%%=*}"
  if ! grep -qE "^[[:space:]]*#?[[:space:]]*${key}=" "$ENV_FILE" 2>/dev/null; then
    printf '%s\n' "$line" >> "$ENV_FILE"
  fi
}

_env_section() {
  local title="$1"
  if ! grep -qF "# --- $title ---" "$ENV_FILE" 2>/dev/null; then
    printf '\n# --- %s ---\n' "$title" >> "$ENV_FILE"
  fi
}

# Prompt for a secret when stdin is a TTY; otherwise skip silently.
_prompt_secret() {
  local key="$1"; local label="$2"
  if _env_has "$key"; then
    ok "$key $(m setv_already_set)"
    return
  fi
  if [ ! -t 0 ]; then
    info "$key $(m setv_skip_noninteractive)"
    _env_append_if_absent "# ${key}="
    return
  fi
  echo ""
  printf "  🐜 %s [%s] (%s): " "$label" "$key" "$(m setv_enter_skip)"
  local val=""
  # -s hides input; fall back to plain read if -s is unsupported
  if read -rs val 2>/dev/null; then echo ""; else read -r val; fi
  if [ -n "$val" ]; then
    printf '%s=%s\n' "$key" "$val" >> "$ENV_FILE"
    ok "$key $(m setv_saved)"
  else
    _env_append_if_absent "# ${key}="
    info "$key $(m setv_skipped)"
  fi
}

# --- create file if missing -------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  info "$(m setv_creating) $ENV_FILE"
  {
    echo "# ============================================================"
    echo "# ARI environment file — auto-generated by setup.sh"
    echo "# Uncomment and edit values as needed. Secrets are never echoed."
    echo "# ============================================================"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE" 2>/dev/null || true
else
  ok "$(m setv_found) $ENV_FILE"
fi

# --- 1) API keys: prompt if missing -----------------------------------------
_env_section "API keys"
_prompt_secret "OPENAI_API_KEY"          "OpenAI API key"
_prompt_secret "ANTHROPIC_API_KEY"       "Anthropic API key"
_prompt_secret "GOOGLE_API_KEY"          "Google (Gemini) API key"
_prompt_secret "S2_API_KEY"              "Semantic Scholar API key"
_env_append_if_absent "# SEMANTIC_SCHOLAR_API_KEY="

# --- 2) LLM / backend (defaults) -------------------------------------------
_env_section "LLM / backend"
_env_append_if_absent "# ARI_BACKEND=ollama"
_env_append_if_absent "# ARI_MODEL=qwen3:8b"
_env_append_if_absent "# ARI_LLM_MODEL="
_env_append_if_absent "# ARI_LLM_API_BASE="
_env_append_if_absent "# LLM_MODEL="
_env_append_if_absent "# LLM_API_BASE="
_env_append_if_absent "# OLLAMA_HOST=http://localhost:11434"
_env_append_if_absent "# OLLAMA_BASE_URL=http://localhost:11434"

# --- 2b) Per-phase LLM model overrides --------------------------------------
# These win over ARI_MODEL/ARI_LLM_MODEL within their phase. Leave blank to
# use the global model. The GUI Settings page writes these automatically.
_env_append_if_absent "# ARI_MODEL_IDEA="
_env_append_if_absent "# ARI_MODEL_CODING="
_env_append_if_absent "# ARI_MODEL_EVAL="
_env_append_if_absent "# ARI_MODEL_PAPER="
_env_append_if_absent "# ARI_MODEL_BFTS="

# --- 3) VLM review ----------------------------------------------------------
_env_section "VLM review"
_env_append_if_absent "# VLM_MODEL=openai/gpt-4o"
_env_append_if_absent "# VLM_REVIEW_ENABLED=true"
_env_append_if_absent "# VLM_REVIEW_THRESHOLD=0.7"
_env_append_if_absent "# VLM_REVIEW_MAX_ITER=3"

# --- 4) ARI paths -----------------------------------------------------------
_env_section "ARI paths"
_env_append_if_absent "# ARI_ROOT=${ARI_ROOT}"
_env_append_if_absent "# ARI_WORK_DIR=/tmp/ari_work"
_env_append_if_absent "# ARI_WORKSPACE="
_env_append_if_absent "# ARI_CHECKPOINT_DIR="
_env_append_if_absent "# ARI_LOG_DIR="
_env_append_if_absent "# ARI_LOG_LEVEL=INFO"
_env_append_if_absent "# ARI_SOURCE_FILE="
# v0.6.0 removed the local JSONL store.
# These legacy keys have no effect and are kept as comments so upgraders
# can delete them manually.
_env_append_if_absent "# ARI_MEMORY_PATH=  # (v0.5.x legacy — ignored under v0.6.0)"
_env_append_if_absent "# ARI_GLOBAL_MEMORY_PATH=  # (v0.5.x legacy — global memory was removed)"

# --- 4b) Memory (Letta) -----------------------------------------------------
# Letta is the sole production memory backend as of v0.6.0.
_env_section "Memory (Letta)"
_env_append_if_absent "# LETTA_BASE_URL=http://localhost:8283"
_env_append_if_absent "# LETTA_API_KEY="
_env_append_if_absent "# LETTA_EMBEDDING_CONFIG=letta-default"
_env_append_if_absent "# LETTA_LLM_CONFIG=letta-default"
_env_append_if_absent "# ARI_MEMORY_BOOTSTRAP_LOCAL_LETTA=auto  # auto|pip|docker|singularity|none"
_env_append_if_absent "# ARI_MEMORY_LETTA_TIMEOUT_S=10"
_env_append_if_absent "# ARI_MEMORY_LETTA_OVERFETCH=200"
_env_append_if_absent "# ARI_TRANSFORM_MEMORY_MAX_ENTRIES=20"
_env_append_if_absent "# ARI_TRANSFORM_MEMORY_MAX_CHARS=2000"
_env_append_if_absent "# ARI_REACT_MEMORY_SEARCH_LIMIT=10"
_env_append_if_absent "# ARI_REACT_MEMORY_MAX_ENTRY_CHARS=0"
# Internal / tests only — do not set unless you know why:
_env_append_if_absent "# ARI_MEMORY_BACKEND=letta  # letta | in_memory (test fake)"
_env_append_if_absent "# ARI_MEMORY_LETTA_DISABLE_SELF_EDIT=true"
_env_append_if_absent "# ARI_MEMORY_ACCESS_LOG=on"
_env_append_if_absent "# ARI_MEMORY_AUTO_RESTORE=true"
_env_append_if_absent "# ARI_CURRENT_NODE_ID=  # runtime-only; set per-node by ari-core"
_env_append_if_absent "# ARI_LETTA_VENV=  # override pip-mode venv path"

# --- 5) ARI limits / scheduling --------------------------------------------
_env_section "ARI limits"
_env_append_if_absent "# ARI_MAX_DEPTH=5"
_env_append_if_absent "# ARI_MAX_NODES=50"
_env_append_if_absent "# ARI_MAX_REACT=80"
_env_append_if_absent "# ARI_MAX_RECURSION_DEPTH="
_env_append_if_absent "# ARI_TIMEOUT_NODE=7200"
_env_append_if_absent "# ARI_PARALLEL=4"
_env_append_if_absent "# ARI_PARENT_RUN_ID="
_env_append_if_absent "# ARI_RETRIEVAL_BACKEND=semantic_scholar"
_env_append_if_absent "# ARI_EXECUTOR="
_env_append_if_absent "# ARI_MAX_CHILD_PROCS="

# --- 6) Container -----------------------------------------------------------
_env_section "Container"
_env_append_if_absent "# ARI_CONTAINER_IMAGE="
_env_append_if_absent "# ARI_CONTAINER_MODE=auto"
_env_append_if_absent "# ARI_CONTAINERS_DIR="
_env_append_if_absent "# APPTAINER_CACHEDIR="
_env_append_if_absent "# SINGULARITY_CACHEDIR="

# --- 7) SLURM ---------------------------------------------------------------
_env_section "SLURM"
_env_append_if_absent "# SLURM_MODE=local"
_env_append_if_absent "# SLURM_SSH_HOST=localhost"
_env_append_if_absent "# SLURM_SSH_USER="
_env_append_if_absent "# SLURM_SSH_PORT=22"
_env_append_if_absent "# SLURM_SSH_KEY="
_env_append_if_absent "# SLURM_SSH_PASSWORD="
_env_append_if_absent "# SLURM_LOG_DIR="
_env_append_if_absent "# SLURM_DEFAULT_PARTITION="
_env_append_if_absent "# SLURM_VALID_PARTITIONS="
_env_append_if_absent "# SLURM_JOB_ID=   # runtime-only; set by Slurm itself"
_env_append_if_absent "# SLURM_CLUSTER_NAME=  # runtime-only; set by Slurm itself"
_env_append_if_absent "# ARI_SLURM_CPUS="
_env_append_if_absent "# ARI_SLURM_MEM_GB="
_env_append_if_absent "# ARI_SLURM_GPUS="
_env_append_if_absent "# ARI_SLURM_WALLTIME=04:00:00"
_env_append_if_absent "# ARI_SLURM_PARTITION="

# --- 8) Orchestrator / viz --------------------------------------------------
_env_section "Orchestrator"
_env_append_if_absent "# ARI_ORCHESTRATOR_PORT="
_env_append_if_absent "# ARI_ORCHESTRATOR_LOGS="
_env_append_if_absent "# ARI_ORCHESTRATOR_DRY_RUN="
_env_append_if_absent "# ARI_ORCHESTRATOR_SSE_ONESHOT="
_env_append_if_absent "# ARI_ORCHESTRATOR_SSE_TIMEOUT="

# --- 9) LaTeX ---------------------------------------------------------------
_env_section "LaTeX"
_env_append_if_absent "# PDFLATEX_PATH=pdflatex"
_env_append_if_absent "# BIBTEX_PATH=bibtex"

# --- 9a) Skill: ari-skill-paper (review rubric) ----------------------------
_env_section "ari-skill-paper"
_env_append_if_absent "# ARI_RUBRIC="
_env_append_if_absent "# ARI_RUBRIC_DIR="
_env_append_if_absent "# ARI_STRICT_DYNAMIC="
_env_append_if_absent "# ARI_NUM_REVIEWS_ENSEMBLE="
_env_append_if_absent "# ARI_NUM_REFLECTIONS="

# --- 9b) Skill: ari-skill-web ----------------------------------------------
_env_section "ari-skill-web"
_env_append_if_absent "# ARI_ALPHAXIV_ENDPOINT=https://api.alphaxiv.org/mcp/v1"

# --- 10) Skill: ari-skill-idea (agentscope vendor) -------------------------
# Used by ari-skill-idea/vendor/virsci/agentscope — studio/online app,
# gradio UI, and ModelScope integration. Leave commented unless you run
# the agentscope web UI / OSS uploads.
_env_section "agentscope (ari-skill-idea vendor)"
_env_append_if_absent "# IP=127.0.0.1"
_env_append_if_absent "# PORT=7860"
_env_append_if_absent "# SESSION_TYPE=filesystem"
_env_append_if_absent "# SECRET_KEY="
_env_append_if_absent "# CLIENT_ID="
_env_append_if_absent "# CLIENT_SECRET="
_env_append_if_absent "# OWNER="
_env_append_if_absent "# REPO="
_env_append_if_absent "# COPILOT_IP="
_env_append_if_absent "# COPILOT_PORT="
_env_append_if_absent "# LOCAL_WORKSTATION=false"
_env_append_if_absent "# MODELSCOPE_ENVIRONMENT="
_env_append_if_absent "# OSS_ACCESS_KEY_ID="
_env_append_if_absent "# OSS_ACCESS_KEY_SECRET="
_env_append_if_absent "# OSS_BUCKET_NAME="
_env_append_if_absent "# OSS_ENDPOINT="

ok "$(m setv_done) ($ENV_FILE)"
