"""Stable exploration-to-manuscript completeness contracts and helpers."""

from ari.manuscript.briefs import build_section_briefs, render_brief_bundle
from ari.manuscript.builder import build_manuscript_context
from ari.manuscript.contracts import (
    EvidenceRecordV1,
    ExplorationSnapshotV1,
    ManuscriptArtifactRefV1,
    ManuscriptAuthoringBindingV1,
    ManuscriptContextV1,
    ManuscriptContractError,
    ManuscriptNodeSnapshotV1,
    ManuscriptReadinessReportV1,
    ManuscriptRequirementProfileV1,
    ManuscriptSegmentRecordV1,
    OmissionManifestV1,
    OmissionV1,
    PublicationDecisionV1,
    PublicationLockV1,
    PublicationSubVerdictV1,
    RepairBudgetV1,
    RequirementResultV1,
    RequirementSpecV1,
    ResearchRepairPlanV1,
    ResearchRepairRequestV1,
    SectionBriefBundleV1,
    SectionBriefV1,
    canonical_digest,
    parse_manuscript_context,
    parse_manuscript_readiness,
    parse_publication_decision,
    parse_repair_plan,
)
from ari.manuscript.coordinator import (
    ManuscriptAuthoringBlocked,
    ManuscriptOutcome,
    compile_manuscript,
)
from ari.manuscript.profiles import generic_empirical_profile, resolve_profile
from ari.manuscript.publication import build_publication_decision
from ari.manuscript.readiness import evaluate_readiness
from ari.manuscript.repair import (
    RepairExecutionResult,
    authority_digest,
    build_repair_plan,
    execute_repair_plan,
)
from ari.manuscript.snapshot import build_exploration_snapshot

__all__ = [
    "EvidenceRecordV1",
    "ExplorationSnapshotV1",
    "ManuscriptArtifactRefV1",
    "ManuscriptAuthoringBindingV1",
    "ManuscriptAuthoringBlocked",
    "ManuscriptContextV1",
    "ManuscriptContractError",
    "ManuscriptNodeSnapshotV1",
    "ManuscriptOutcome",
    "ManuscriptReadinessReportV1",
    "ManuscriptRequirementProfileV1",
    "ManuscriptSegmentRecordV1",
    "OmissionManifestV1",
    "OmissionV1",
    "PublicationDecisionV1",
    "PublicationLockV1",
    "PublicationSubVerdictV1",
    "RepairBudgetV1",
    "RepairExecutionResult",
    "RequirementResultV1",
    "RequirementSpecV1",
    "ResearchRepairPlanV1",
    "ResearchRepairRequestV1",
    "SectionBriefBundleV1",
    "SectionBriefV1",
    "authority_digest",
    "build_exploration_snapshot",
    "build_manuscript_context",
    "build_publication_decision",
    "build_repair_plan",
    "build_section_briefs",
    "canonical_digest",
    "compile_manuscript",
    "evaluate_readiness",
    "execute_repair_plan",
    "generic_empirical_profile",
    "parse_manuscript_context",
    "parse_manuscript_readiness",
    "parse_publication_decision",
    "parse_repair_plan",
    "render_brief_bundle",
    "resolve_profile",
]
