#!/usr/bin/env python3
"""F07 — rubric tree (graphviz layout → TikZ).

Reads:  shared/figures/data/F07_rubric.yaml
Writes: shared/figures/dot/F07_rubric_tree.dot
        shared/figures/tikz/F07_rubric_tree.tex (via dot2tex)
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import yaml

THIS = Path(__file__).resolve().parent
DATA = THIS.parent / "data" / "F07_rubric.yaml"
DOT  = THIS.parent / "dot"  / "F07_rubric_tree.dot"
TIKZ = THIS.parent / "tikz" / "F07_rubric_tree.tex"

AUTOGEN_HEADER = "% AUTOGENERATED by scripts/rubric_render.py — DO NOT EDIT\n"


def _synthetic_rubric() -> dict:
    return {
        "title": "PaperBench rubric",
        "categories": [
            {"name": "clarity",   "weight": 0.20, "leaves": ["abstract", "structure", "language"]},
            {"name": "novelty",   "weight": 0.20, "leaves": ["idea",     "comparison"]},
            {"name": "rigor",     "weight": 0.30, "leaves": ["theory",   "experiments", "ablation"]},
            {"name": "impact",    "weight": 0.20, "leaves": ["scope",    "applicability"]},
            {"name": "ethics",    "weight": 0.10, "leaves": ["risks"]},
        ],
    }


def _write_dot(r: dict) -> None:
    DOT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "digraph R {",
        "  graph [rankdir=LR, ranksep=0.5, nodesep=0.3];",
        "  node  [shape=box, style=\"rounded\", fontsize=10];",
        f'  root [label="{r["title"]}"];',
    ]
    for i, c in enumerate(r["categories"]):
        cid = f"c{i}"
        lines.append(f'  {cid} [label="{c["name"]}\\nw={c["weight"]:.2f}"];')
        lines.append(f"  root -> {cid};")
        for j, leaf in enumerate(c["leaves"]):
            lid = f"{cid}l{j}"
            lines.append(f'  {lid} [shape=ellipse, label="{leaf}"];')
            lines.append(f"  {cid} -> {lid};")
    lines.append("}")
    DOT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_tikz() -> None:
    if shutil.which("dot2tex") is None:
        print("[rubric_render] dot2tex not found; skipping TikZ generation", file=sys.stderr)
        return
    TIKZ.parent.mkdir(parents=True, exist_ok=True)
    body = subprocess.check_output(
        # texmode=verbatim (not -tmath): plain upright label text. -tmath put
        # every label in math mode, which italicised words and dropped the
        # inter-word space in "PaperBench rubric" (-> "PaperBenchrubric").
        ["dot2tex", "--figonly", "--crop", "--texmode=verbatim", str(DOT)],
        text=True,
    )
    TIKZ.write_text(AUTOGEN_HEADER + body, encoding="utf-8")


def render_rubric(out_dir: Path | None = None) -> Path:
    rubric = yaml.safe_load(DATA.read_text(encoding="utf-8")) if DATA.exists() else _synthetic_rubric()
    _write_dot(rubric)
    _write_tikz()
    return DOT


if __name__ == "__main__":
    p = render_rubric()
    print(f"wrote {p}")
