/* selftest.c — LOCAL developer harness for the GEMM task (handoff study task A).
 *
 * NOT the evaluator and NOT used for scoring. Runs your candidate gemm() on the
 * square problem and reports correctness (same contraction-length eps bound as
 * the evaluator) + an estimated speedup vs the naive ijl baseline. The evaluator
 * uses several shapes and fresh data, so a PASS is a strong-not-complete
 * predictor; the evaluator remains authoritative.
 *
 * Build:  make selftest        Run:  ./selftest
 *
 * Do NOT edit this file or call BLAS; edit candidate_gemm.c. The harness
 * provides main(); selftest links against your gemm() from candidate_gemm.c.
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <omp.h>
#include "gemm_kernel.h"

static int env_int(const char *name, int dflt) {
    const char *v = getenv(name);
    if (!v || !*v) return dflt;
    int x = atoi(v);
    return x > 0 ? x : dflt;
}

#define C_EPS 8.0
static const double FP64_U = 1.1102230246251565e-16; /* 2^-53 */

static double now_sec(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec + (double)t.tv_nsec * 1e-9;
}
static double gamma_k(long k) {
    double ku = (double)k * FP64_U;
    return ku >= 1.0 ? INFINITY : ku / (1.0 - ku);
}

/* naive ijl reference (distinct symbol so it links alongside gemm()). */
static void gemm_ref(int n, int m, int p,
                     const double *A, const double *B, double *C) {
    for (int i = 0; i < n; ++i)
        for (int j = 0; j < m; ++j) {
            double s = 0.0;
            for (int l = 0; l < p; ++l) s += A[(long)i * p + l] * B[(long)l * m + j];
            C[(long)i * m + j] = s;
        }
}

int main(void) {
    const int n = env_int("ARI_GEMM_N", 512);
    const int m = n, p = n;
    const int threads = env_int("ARI_GEMM_THREADS", 16);
    const int warmup = 1, reps = 3;
    omp_set_num_threads(threads);

    double *A = malloc(sizeof(double) * (size_t)n * p);
    double *B = malloc(sizeof(double) * (size_t)p * m);
    double *C = malloc(sizeof(double) * (size_t)n * m);
    double *Cref = malloc(sizeof(double) * (size_t)n * m);
    double *Cbnd = malloc(sizeof(double) * (size_t)n * m);  /* |A| @ |B| */
    double *absA = malloc(sizeof(double) * (size_t)n * p);
    double *absB = malloc(sizeof(double) * (size_t)p * m);
    srand(7);
    for (long i = 0; i < (long)n * p; ++i) { A[i] = (double)rand() / RAND_MAX * 2 - 1; absA[i] = fabs(A[i]); }
    for (long i = 0; i < (long)p * m; ++i) { B[i] = (double)rand() / RAND_MAX * 2 - 1; absB[i] = fabs(B[i]); }

    gemm_ref(n, m, p, A, B, Cref);
    gemm_ref(n, m, p, absA, absB, Cbnd);

    for (int w = 0; w < warmup; ++w) gemm(n, m, p, A, B, C);
    double tc = 0.0;
    for (int r = 0; r < reps; ++r) { double t0 = now_sec(); gemm(n, m, p, A, B, C); tc += now_sec() - t0; }
    tc /= reps;
    double tb = 0.0;
    for (int r = 0; r < reps; ++r) { double t0 = now_sec(); gemm_ref(n, m, p, A, B, Cref); tb += now_sec() - t0; }
    tb /= reps;
    /* recompute a clean reference (the timing loop above reused Cref) */
    gemm_ref(n, m, p, A, B, Cref);

    double g = gamma_k(p);
    int ok = 1; double max_rel = 0.0;
    for (long idx = 0; idx < (long)n * m; ++idx) {
        double resid = fabs(C[idx] - Cref[idx]);
        if (resid > C_EPS * g * Cbnd[idx]) ok = 0;
        double denom = fabs(Cref[idx]);
        if (denom > 0.0) { double rel = resid / denom; if (rel > max_rel) max_rel = rel; }
    }
    double speedup = (tc > 0.0) ? (tb / tc) : 0.0;
    printf("problem: %dx%dx%d  omp_threads=%d\n", n, p, m, threads);
    printf("candidate_sec=%.5f  baseline_naive_sec=%.5f  speedup~%.1fx  correct=%s  max_rel=%.2e\n",
           tc, tb, speedup, ok ? "yes" : "NO", max_rel);
    if (ok)
        printf("SELFTEST: PASS  (correct; ~%.1fx vs naive baseline)\n", speedup);
    else
        printf("SELFTEST: FAIL  (incorrect output => the evaluator scores 0; fix correctness first)\n");

    free(A); free(B); free(C); free(Cref); free(Cbnd); free(absA); free(absB);
    return ok ? 0 : 1;
}
