/* selftest.c — LOCAL developer harness for the 3-D Jacobi stencil task.
 *
 * NOT the evaluator and NOT used for scoring. Runs your candidate jacobi() on a
 * single grid and reports correctness (same nt-scaled eps bound as the
 * evaluator) + an estimated speedup vs the naive single-thread baseline. The
 * evaluator uses several grid shapes and fresh data, so a PASS is a
 * strong-not-complete predictor; the evaluator remains authoritative.
 *
 * Build:  make selftest        Run:  ./selftest      (or: make check)
 *
 * Do NOT edit this file; edit candidate_stencil.c. The harness provides main();
 * selftest links against your jacobi() from candidate_stencil.c.
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include <omp.h>
#include "stencil_kernel.h"

static int env_int(const char *name, int dflt) {
    const char *v = getenv(name);
    if (!v || !*v) return dflt;
    int x = atoi(v);
    return x > 0 ? x : dflt;
}

#define C_EPS 8.0
static const double FP64_U = 1.1102230246251565e-16; /* 2^-53 */

static double now_sec(void) {
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return (double)t.tv_sec + (double)t.tv_nsec * 1e-9;
}
static double gamma_k(long k) {
    double ku = (double)k * FP64_U;
    return ku >= 1.0 ? INFINITY : ku / (1.0 - ku);
}

/* naive single-thread reference (distinct symbol so it links alongside jacobi()). */
static void jacobi_ref(int nx, int ny, int nz, int nt,
                       const double *u0, double *u) {
    const double c0 = 0.5, cw = 1.0 / 12.0;
    const size_t N = (size_t)nx * ny * nz;
    const size_t si = (size_t)ny * nz, sj = (size_t)nz;
    double *cur = malloc(sizeof(double) * N);
    double *nxt = malloc(sizeof(double) * N);
    memcpy(cur, u0, sizeof(double) * N);
    memcpy(nxt, u0, sizeof(double) * N);
    for (int t = 0; t < nt; ++t) {
        for (int i = 1; i < nx - 1; ++i)
            for (int j = 1; j < ny - 1; ++j)
                for (int k = 1; k < nz - 1; ++k) {
                    size_t c = ((size_t)i * ny + j) * nz + k;
                    nxt[c] = c0 * cur[c]
                           + cw * (cur[c - si] + cur[c + si]
                                 + cur[c - sj] + cur[c + sj]
                                 + cur[c - 1]  + cur[c + 1]);
                }
        double *tmp = cur; cur = nxt; nxt = tmp;
    }
    memcpy(u, cur, sizeof(double) * N);
    free(cur); free(nxt);
}

int main(void) {
    const int nx = env_int("ARI_STENCIL_NX", 192);
    const int ny = nx, nz = nx;
    const int nt = env_int("ARI_STENCIL_NT", 30);
    const int threads = env_int("ARI_STENCIL_THREADS", 16);
    const int warmup = 1, reps = 3;
    const size_t N = (size_t)nx * ny * nz;
    omp_set_num_threads(threads);

    double *u0 = malloc(sizeof(double) * N);
    double *u  = malloc(sizeof(double) * N);
    double *ur = malloc(sizeof(double) * N);
    if (!u0 || !u || !ur) { fprintf(stderr, "oom\n"); return 2; }
    srand(7);
    double amax = 0.0;
    for (size_t i = 0; i < N; ++i) {
        u0[i] = (double)rand() / RAND_MAX * 2.0 - 1.0;
        double a = fabs(u0[i]); if (a > amax) amax = a;
    }
    if (amax == 0.0) amax = 1.0;

    jacobi_ref(nx, ny, nz, nt, u0, ur);

    for (int w = 0; w < warmup; ++w) jacobi(nx, ny, nz, nt, u0, u);
    double tc = 0.0;
    for (int r = 0; r < reps; ++r) { double t0 = now_sec(); jacobi(nx, ny, nz, nt, u0, u); tc += now_sec() - t0; }
    tc /= reps;
    double tb = 0.0;
    for (int r = 0; r < reps; ++r) { double t0 = now_sec(); jacobi_ref(nx, ny, nz, nt, u0, ur); tb += now_sec() - t0; }
    tb /= reps;
    jacobi_ref(nx, ny, nz, nt, u0, ur); /* clean reference after timing */

    double bound = C_EPS * gamma_k(7) * (double)(nt > 0 ? nt : 1) * amax;
    int ok = 1; double max_abs = 0.0;
    for (size_t idx = 0; idx < N; ++idx) {
        double resid = fabs(u[idx] - ur[idx]);
        if (resid > bound) ok = 0;
        if (resid > max_abs) max_abs = resid;
    }
    double speedup = (tc > 0.0) ? (tb / tc) : 0.0;
    printf("grid: %dx%dx%d  sweeps=%d  omp_threads=%d\n", nx, ny, nz, nt, threads);
    printf("candidate_sec=%.5f  baseline_naive_sec=%.5f  speedup~%.1fx  correct=%s  max_abs_err=%.2e  bound=%.2e\n",
           tc, tb, speedup, ok ? "yes" : "NO", max_abs, bound);
    if (ok)
        printf("SELFTEST: PASS  (correct; ~%.1fx vs naive baseline)\n", speedup);
    else
        printf("SELFTEST: FAIL  (incorrect output => the evaluator scores 0; fix correctness first)\n");

    free(u0); free(u); free(ur);
    return ok ? 0 : 1;
}
