"""Generate the manuscript's result tables from the derived analysis, not by hand.

WHY. Transcription is where this manuscript has lost numbers. A manual audit
found fourteen wrong or unsourced values in one sitting, and a later machine
check found two more that the eye had passed -- band ratios recomputed from the
rounded figures printed in a table rather than from the values behind them. Every
number a result table states should come out of the program that produced it.

WHAT IT EMITS, from ``reviewer_response_analysis.json`` and the per-task
``analysis.json`` a collected campaign leaves behind:

  descriptive   mean / median / sd / min / max / geomean of the final
                remeasured speedup, per task and arm
  contrasts     the two primary paired contrasts per task, with CI and p
  absolute      achieved GF/s per arm against the measured ceiling
                (delegates to aggregate_flops.py, which knows the flop counts)

It prints rows only. The surrounding table environment, caption and label stay in
the manuscript, because those carry the claims and should be written by a person.

USAGE
    python emit_paper_tables.py --derived report_temp/tools/reviewer_response_analysis.json
    python emit_paper_tables.py --derived ... --which descriptive
"""
import argparse
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
TASKS = ("gemm", "spmm", "stencil")
ARMS = ("code_only", "evidence_only", "evidence_plus_reflection")
ARM_TEX = {"code_only": r"\armW{}", "evidence_only": r"\armE{}",
           "evidence_plus_reflection": r"\armS{}"}
CONTRASTS = (("evidence_only_minus_code_only", r"E--W"),
             ("evidence_plus_reflection_minus_evidence_only", r"S--E"))


def descriptive(derived: dict) -> list[str]:
    rows = []
    for task in TASKS:
        for arm in ARMS:
            s = ((derived.get("outcomes") or {}).get(task) or {}).get(arm)
            if not s:
                continue
            rows.append(
                rf"\texttt{{{task}}} & {ARM_TEX[arm]} & "
                rf"{s['mean']:.2f} & {s['median']:.2f} & {s['sd']:.2f} & "
                rf"{s['min']:.2f} & {s['max']:.2f} & {s['geomean']:.2f} \\")
    return rows


def contrasts(task_analyses: dict) -> list[str]:
    rows = []
    for task in TASKS:
        a = task_analyses.get(task)
        if not a:
            continue
        for key, label in CONTRASTS:
            rec = None
            for c in (a.get("primary") or a.get("contrasts") or []):
                if isinstance(c, dict) and c.get("key") == key:
                    rec = c
                    break
            if not rec:
                continue
            lo, hi = rec.get("ci_low"), rec.get("ci_high")
            p = rec.get("p_value")
            rows.append(
                rf"\texttt{{{task}}} & {label} & {rec.get('estimate', float('nan')):+.3f} & "
                rf"$[{lo:+.3f},\ {hi:+.3f}]$ & {p:.3f} \\"
                if lo is not None and hi is not None and p is not None else
                rf"\texttt{{{task}}} & {label} & (incomplete) \\")
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--derived", required=True,
                    help="reviewer_response_analysis.json")
    ap.add_argument("--analysis-root", default=None,
                    help="collected campaign root holding <task>/analysis.json")
    ap.add_argument("--which", default="all",
                    choices=("all", "descriptive", "contrasts"))
    args = ap.parse_args()

    derived = json.loads(pathlib.Path(args.derived).read_text())
    task_analyses = {}
    if args.analysis_root:
        root = pathlib.Path(args.analysis_root)
        for t in TASKS:
            p = root / t / "analysis.json"
            if p.is_file():
                task_analyses[t] = json.loads(p.read_text())

    if args.which in ("all", "descriptive"):
        print("% descriptive -- generated by workspace/tools/emit_paper_tables.py")
        for r in descriptive(derived):
            print(r)
        print()
    if args.which in ("all", "contrasts"):
        if not task_analyses:
            print("% contrasts: pass --analysis-root <campaign root> to emit these")
        else:
            print("% contrasts -- generated by workspace/tools/emit_paper_tables.py")
            for r in contrasts(task_analyses):
                print(r)
    print()
    print("% absolute performance: workspace/tools/aggregate_flops.py "
          "--root <campaign root> --by arm --latex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
